"""Compatibility facade for the versioned CapCut track/template matrix."""

from track_template_matrix import (
    A10_TEXT_TRACK_BY_COLOR,
    A12_INDEX,
    CANONICAL_TRACKS,
    DEFAULT_TRACK_TEMPLATE,
    FULL_SPAN_ROLES,
    FOREIGN_VIRAL_DIALOGUE_TEMPLATE_PROFILE,
    GRID_LINE_BUDGETS,
    HUMAN_GRID_ROWS,
    LINE_LIMITS,
    LOGICAL_ROLE_BY_LAYOUT,
    LOGICAL_ROLE_BY_TRACK,
    MAX_LINE_COUNT_BY_ROLE,
    MAX_LINE_LENGTH_BY_ROLE,
    OPTIONAL_FULL_SPAN_ROLES,
    PINNED_ASSETS,
    ROLE_LINE_BUDGETS,
    SPEAKER_BLUE_DIALOGUE_WHITE_TWO_LINE,
    STATE_TRACK_BY_EFFECT,
    TEMPLATE_PROFILE,
    TEMPLATE_PROFILE_BY_TRACK_LAYOUT,
    TRACK_INDEX,
    TRACK_LAYOUT,
    TRACK_LAYOUT_BY_TEMPLATE_PROFILE,
    TRACK_TEMPLATE_PROFILES,
    V2_LOGICAL_ROLE_BY_TRACK,
    V2_TEMPLATE_PROFILE,
    V2_TRACK_LAYOUT,
    V3_TEMPLATE_PROFILE,
    V3_TRACK_LAYOUT,
    VISUAL_TRACK_COUNT,
    YELLOW_RED_YELLOW_EMPHASIS,
    LineBudget,
    TrackTemplateProfile,
    profile_supports_role,
    state_track_by_effect,
    template_profiles_for_layout,
    track_template_profile,
)

__all__ = tuple(name for name in globals() if not name.startswith("_"))
