"""AUTO-GENERATED by scripts/sync_shared_workflow_harness.py.

DO NOT EDIT. This file is a byte-identical vendored copy of the
canonical shared/workflow-harness/core modules. Edit the canonical
source and re-run sync_shared_workflow_harness.py.

WORKFLOW_HARNESS_SOURCE_VERSION: shared-gates-separated-lanes-v2
"""
from __future__ import annotations

# === BEGIN CANONICAL MODULE: ledger.py ===
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Iterable


class BrokenChainError(Exception):
    """Raised when an appended event references a non-existent
    previous_event_id, or when the event_id collides with an existing one."""

    def __init__(self, event_id: str, previous_event_id: str | None):
        super().__init__(
            f"BROKEN_CHAIN event_id={event_id} "
            f"previous_event_id={previous_event_id}"
        )
        self.event_id = event_id
        self.previous_event_id = previous_event_id


class DuplicateEventError(Exception):
    def __init__(self, event_id: str):
        super().__init__(f"DUPLICATE_EVENT event_id={event_id}")
        self.event_id = event_id


@dataclass
class LedgerStore:
    """In-memory append-only event log.

    Validations performed on append:
    - event_id must be unique within the store.
    - previous_event_id must reference an existing event, or be None only
      when the store is empty (genesis).
    """

    events: list[dict] = field(default_factory=list)
    _by_id: dict[str, dict] = field(default_factory=dict)

    def append(self, event: dict) -> dict:
        if not isinstance(event, dict):
            raise TypeError("ledger event must be a dict")
        event_id = event.get("event_id")
        prev = event.get("previous_event_id")
        if not event_id:
            raise BrokenChainError(None, prev)
        if event_id in self._by_id:
            raise DuplicateEventError(event_id)
        # Genesis rule: the very first event must have previous_event_id=None.
        if not self.events:
            if prev is not None:
                raise BrokenChainError(event_id, prev)
        else:
            if prev is None:
                raise BrokenChainError(event_id, None)
            if prev not in self._by_id:
                raise BrokenChainError(event_id, prev)
        # Freeze a shallow copy to avoid callers mutating history.
        stored = dict(event)
        self.events.append(stored)
        self._by_id[event_id] = stored
        return stored

    def extend(self, events: Iterable[dict]) -> None:
        for e in events:
            self.append(e)

    def latest_event_id(self) -> str | None:
        return self.events[-1]["event_id"] if self.events else None

    def to_jsonl(self) -> str:
        return "\n".join(json.dumps(e, ensure_ascii=False) for e in self.events)

    @classmethod
    def from_jsonl(cls, text: str) -> "LedgerStore":
        store = cls()
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            store.append(json.loads(line))
        return store
# === END CANONICAL MODULE: ledger.py ===

# === BEGIN CANONICAL MODULE: state_projection.py ===
from __future__ import annotations

from typing import Iterable


GATE_ORDER = [
    "G00",
    "G10",
    "G20",
    "G30",
    "G40",
    "G50",
    "G60",
    "G60.USER",
    "G70",
    "G80",
    "G90",
]


class StateLedgerMismatch(Exception):
    """Raised when a candidate manual_gate_state.json disagrees with the
    projection rebuilt from the ledger."""

    def __init__(self, field_name: str, ledger_value, candidate_value):
        super().__init__(
            f"STATE_LEDGER_MISMATCH field={field_name} "
            f"ledger={ledger_value!r} candidate={candidate_value!r}"
        )
        self.field_name = field_name
        self.ledger_value = ledger_value
        self.candidate_value = candidate_value


def _gate_index(gate: str | None) -> int:
    if gate is None:
        return -1
    if gate not in GATE_ORDER:
        return -1
    return GATE_ORDER.index(gate)


def rebuild_state(events: Iterable[dict]) -> dict:
    """Project the current manual_gate_state.json from a ledger event list.

    The projection captures:
    - episode_id, lane, content_profile, production_mode, requested_target
      (locked at WORKFLOW_CREATED or the first G00 event).
    - current_gate / current_subgate / last_passed_gate derived from
      GATE_STARTED / GATE_PASSED / GATE_FAILED events.
    - projection_of_ledger_event_id = the last event id seen.
    """
    events = list(events)
    if not events:
        raise ValueError("STATE_REBUILD_EMPTY_LEDGER")

    genesis = events[0]
    state = {
        "schema_version": "manual-gate-state-v1",
        "episode_id": genesis.get("episode_id"),
        "lane": genesis.get("lane"),
        "content_profile": genesis.get("content_profile", "general_shorts"),
        "production_mode": genesis.get("production_mode", "not_applicable"),
        "requested_target": genesis.get("requested_target", "design_only"),
        "current_gate": None,
        "current_subgate": None,
        "last_passed_gate": None,
        "source_fingerprint": genesis.get("source_fingerprint", ""),
        "current_authoritative_artifact": None,
        "current_authoritative_sha256": None,
        "next_user_action": None,
        "auto_external_call": False,
        "release_allowed": False,
        "projection_of_ledger_event_id": genesis.get("event_id"),
        "contract_mode": genesis.get("contract_mode", "V2_CANONICAL"),
    }

    last_passed_idx = -1
    for ev in events:
        et = ev.get("event_type")
        gate = ev.get("gate")
        if et == "WORKFLOW_CREATED":
            # Promote any G00-scoped fields locked at creation.
            for k in (
                "content_profile",
                "production_mode",
                "requested_target",
                "source_fingerprint",
            ):
                if k in ev:
                    state[k] = ev[k]
        if et == "GATE_STARTED" and gate is not None:
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
        elif et == "GATE_PASSED" and gate is not None:
            idx = _gate_index(gate)
            if idx > last_passed_idx:
                last_passed_idx = idx
                state["last_passed_gate"] = gate
            # After a pass, the current gate stays at the passed gate until
            # the next GATE_STARTED event arrives.
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
            if ev.get("artifact_path"):
                state["current_authoritative_artifact"] = ev["artifact_path"]
            if ev.get("artifact_sha256"):
                state["current_authoritative_sha256"] = ev["artifact_sha256"]
        elif et == "GATE_FAILED" and gate is not None:
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
        elif et == "OWNER_TRANSFERRED":
            state["next_user_action"] = None
        elif et == "USER_VISUAL_PASS":
            state["next_user_action"] = None
        elif et == "UPLOAD_APPROVED":
            state["release_allowed"] = True
        state["projection_of_ledger_event_id"] = ev.get("event_id")

    return state


# Fields that must match exactly between a candidate state file and the
# ledger projection. Other fields (e.g. display timestamps) are advisory.
_MATCHED_FIELDS = (
    "episode_id",
    "lane",
    "content_profile",
    "production_mode",
    "current_gate",
    "current_subgate",
    "last_passed_gate",
    "current_authoritative_artifact",
    "current_authoritative_sha256",
    "projection_of_ledger_event_id",
    "release_allowed",
)


def compare_and_assert(ledger_projection: dict, candidate: dict) -> None:
    """Raise StateLedgerMismatch if the candidate state disagrees with the
    ledger projection on any matched field."""
    for field_name in _MATCHED_FIELDS:
        ledger_value = ledger_projection.get(field_name)
        candidate_value = candidate.get(field_name)
        if ledger_value != candidate_value:
            raise StateLedgerMismatch(field_name, ledger_value, candidate_value)
# === END CANONICAL MODULE: state_projection.py ===

# === BEGIN CANONICAL MODULE: gate_validation.py ===
from __future__ import annotations


SCHEMA_VERSION = "gate-result-v1"

ALLOWED_AUTO_ADVANCE_CLASSES = {
    "NONE",
    "DETERMINISTIC_ONLY",
    "LLM_CALL_FORBIDDEN",
    "PAID_ACTION_FORBIDDEN",
    "UPLOAD_FORBIDDEN",
}

# Any class value outside the allowed set is treated as a forbidden attempt
# to authorize automatic LLM / paid / upload work.
FORBIDDEN_AUTO_ADVANCE_CLASSES = {
    "LLM_CALL_ALLOWED",
    "PAID_ACTION_ALLOWED",
    "UPLOAD_ALLOWED",
}


class ForbiddenAdvanceClass(Exception):
    """Raised when a validator result asks the runner to perform automatic
    LLM / paid / upload work — which the validator is never allowed to do."""

    def __init__(self, auto_advance_class: str):
        super().__init__(
            f"FORBIDDEN_ADVANCE_CLASS auto_advance_class={auto_advance_class}"
        )
        self.auto_advance_class = auto_advance_class


def validate_gate(
    *,
    lane: str,
    gate: str,
    subgate: str | None,
    validated_inputs: list[dict],
    evidence: list[dict],
    errors: list[dict],
    warnings: list[dict],
    next_action: str,
    auto_advance_allowed: bool,
    auto_advance_class: str,
    status: str | None = None,
    reason_code: str | None = None,
) -> dict:
    """Construct a gate_result document.

    The validator itself never executes any next action; the runner does.
    The runner must reject any result whose auto_advance_class requests
    automatic LLM, paid, or upload work.
    """
    if auto_advance_class in FORBIDDEN_AUTO_ADVANCE_CLASSES:
        raise ForbiddenAdvanceClass(auto_advance_class)
    if auto_advance_class not in ALLOWED_AUTO_ADVANCE_CLASSES:
        raise ForbiddenAdvanceClass(auto_advance_class)

    # If errors are present the status cannot be PASS.
    derived_status = status
    if derived_status is None:
        derived_status = "FAIL" if errors else "PASS"

    result = {
        "schema_version": SCHEMA_VERSION,
        "status": derived_status,
        "reason_code": reason_code,
        "lane": lane,
        "gate": gate,
        "subgate": subgate,
        "validated_inputs": list(validated_inputs),
        "evidence": list(evidence),
        "errors": list(errors),
        "warnings": list(warnings),
        "next_action": next_action,
        "auto_advance_allowed": bool(auto_advance_allowed),
        "auto_advance_class": auto_advance_class,
    }
    return result
# === END CANONICAL MODULE: gate_validation.py ===

# === BEGIN CANONICAL MODULE: cost_guard.py ===
from __future__ import annotations

from dataclasses import dataclass


class CostOverrun(Exception):
    """Raised when a paid action would exceed the configured budget."""

    def __init__(self, kind: str, requested, limit):
        super().__init__(
            f"COST_OVERRUN kind={kind} requested={requested} limit={limit}"
        )
        self.kind = kind
        self.requested = requested
        self.limit = limit


@dataclass
class CostGuard:
    episode_budget_usd: float | None
    max_model_input_tokens_per_gate: int | None
    max_model_output_tokens_per_gate: int | None
    max_paid_tts_chars: int | None
    paid_tts_authorization: dict
    spent_tts_chars: int = 0
    spent_model_input_tokens: int = 0
    spent_model_output_tokens: int = 0
    spent_usd: float = 0.0

    def can_authorize_paid_action(self) -> bool:
        """A paid action requires both a non-zero episode budget AND an
        explicit authorization scope. No budget => no paid action."""
        if self.episode_budget_usd is None or self.episode_budget_usd <= 0:
            return False
        status = self.paid_tts_authorization.get("status")
        scope = self.paid_tts_authorization.get("scope")
        if status != "AUTHORIZED_FOR_EPISODE":
            return False
        if scope in (None, "none"):
            return False
        return True

    def can_spend_tts(self, *, chars: int) -> bool:
        """Check whether a paid TTS spend of `chars` fits within both the
        authorization limit and the episode budget."""
        if chars < 0:
            return False
        if not self.can_authorize_paid_action():
            return False
        limit = self.paid_tts_authorization.get("max_chars")
        if limit is not None and self.spent_tts_chars + chars > limit:
            return False
        if (
            self.max_paid_tts_chars is not None
            and self.spent_tts_chars + chars > self.max_paid_tts_chars
        ):
            return False
        return True

    def record_tts_spend(self, *, chars: int) -> None:
        if not self.can_spend_tts(chars=chars):
            raise CostOverrun("tts_chars", chars, self.max_paid_tts_chars)
        self.spent_tts_chars += chars

    def can_spend_model_tokens(self, *, input_tokens: int, output_tokens: int) -> bool:
        if self.max_model_input_tokens_per_gate is not None:
            if self.spent_model_input_tokens + input_tokens > self.max_model_input_tokens_per_gate:
                return False
        if self.max_model_output_tokens_per_gate is not None:
            if self.spent_model_output_tokens + output_tokens > self.max_model_output_tokens_per_gate:
                return False
        return True
# === END CANONICAL MODULE: cost_guard.py ===

# === BEGIN CANONICAL MODULE: context_manifest.py ===
from __future__ import annotations

import hashlib
from dataclasses import dataclass, field


SCHEMA_VERSION = "context-manifest-v1"

DEFAULT_ESTIMATOR_VERSION = "chars_div_4_v1"


@dataclass
class ContextManifest:
    lane: str
    gate: str
    subgate: str | None
    run_id: str
    loaded_files: list[dict] = field(default_factory=list)
    excluded_by_policy: list[str] = field(default_factory=list)
    provider_input_tokens: int | None = None
    estimated_input_tokens: int | None = None
    estimator_version: str = DEFAULT_ESTIMATOR_VERSION
    unrelated_lane_reads: int = 0
    legacy_reads: int = 0
    full_srt_injected: bool = False
    contract_mode: str = "V2_CANONICAL"
    status: str = "PASS"

    def add_loaded_file(self, path: str, content: bytes | str | None = None) -> None:
        entry = {"path": path}
        if content is not None:
            if isinstance(content, str):
                content = content.encode("utf-8")
            entry["sha256"] = hashlib.sha256(content).hexdigest().upper()
            entry["chars"] = len(content)
        self.loaded_files.append(entry)

    def add_excluded(self, category: str) -> None:
        if category not in self.excluded_by_policy:
            self.excluded_by_policy.append(category)

    def set_estimated_tokens_from_chars(self, total_chars: int) -> None:
        # Simple deterministic estimator; production may override.
        self.estimated_input_tokens = max(0, total_chars // 4)
        self.estimator_version = DEFAULT_ESTIMATOR_VERSION

    def to_dict(self) -> dict:
        if self.provider_input_tokens is None and self.estimated_input_tokens is None:
            raise ValueError(
                "CONTEXT_MANIFEST_MISSING_TOKENS: set provider_input_tokens "
                "or estimated_input_tokens"
            )
        return {
            "schema_version": SCHEMA_VERSION,
            "lane": self.lane,
            "gate": self.gate,
            "subgate": self.subgate,
            "run_id": self.run_id,
            "loaded_files": list(self.loaded_files),
            "excluded_by_policy": list(self.excluded_by_policy),
            "provider_input_tokens": self.provider_input_tokens,
            "estimated_input_tokens": self.estimated_input_tokens,
            "estimator_version": self.estimator_version
            if self.provider_input_tokens is None
            else None,
            "unrelated_lane_reads": self.unrelated_lane_reads,
            "legacy_reads": self.legacy_reads,
            "full_srt_injected": self.full_srt_injected,
            "contract_mode": self.contract_mode,
            "status": self.status,
        }
# === END CANONICAL MODULE: context_manifest.py ===


# WORKFLOW_HARNESS_SOURCE_VERSION = 'shared-gates-separated-lanes-v2'
# WORKFLOW_HARNESS_SOURCE_SHA256 = '31F89982FF680DA94C17995BBD933F34F2A68F0780F6EFF8BF00CFEFF08EEDE6'
# DO NOT EDIT — regenerate via scripts/sync_shared_workflow_harness.py

