"""AUTO-GENERATED by scripts/sync_shared_workflow_harness.py.

DO NOT EDIT. This file is a byte-identical vendored copy of the
canonical shared/workflow-harness/core modules. Edit the canonical
source and re-run sync_shared_workflow_harness.py.

WORKFLOW_HARNESS_SOURCE_VERSION: shared-gates-separated-lanes-v2
"""
from __future__ import annotations

# === BEGIN CANONICAL MODULE: ledger.py ===
import json
from dataclasses import dataclass, field
from typing import Iterable


class BrokenChainError(Exception):
    """Raised when an appended event references a non-existent
    previous_event_id, or when the event_id collides with an existing one."""

    def __init__(self, event_id: str, previous_event_id: str | None):
        super().__init__(
            f"BROKEN_CHAIN event_id={event_id} "
            f"previous_event_id={previous_event_id}"
        )
        self.event_id = event_id
        self.previous_event_id = previous_event_id


class DuplicateEventError(Exception):
    def __init__(self, event_id: str):
        super().__init__(f"DUPLICATE_EVENT event_id={event_id}")
        self.event_id = event_id


@dataclass
class LedgerStore:
    """In-memory append-only event log.

    Validations performed on append:
    - event_id must be unique within the store.
    - previous_event_id must reference an existing event, or be None only
      when the store is empty (genesis).
    """

    events: list[dict] = field(default_factory=list)
    _by_id: dict[str, dict] = field(default_factory=dict)

    def append(self, event: dict) -> dict:
        if not isinstance(event, dict):
            raise TypeError("ledger event must be a dict")
        event_id = event.get("event_id")
        prev = event.get("previous_event_id")
        if not event_id:
            raise BrokenChainError(None, prev)
        if event_id in self._by_id:
            raise DuplicateEventError(event_id)
        # Genesis rule: the very first event must have previous_event_id=None.
        if not self.events:
            if prev is not None:
                raise BrokenChainError(event_id, prev)
        else:
            if prev is None:
                raise BrokenChainError(event_id, None)
            if prev not in self._by_id:
                raise BrokenChainError(event_id, prev)
        # Freeze a shallow copy to avoid callers mutating history.
        stored = dict(event)
        self.events.append(stored)
        self._by_id[event_id] = stored
        return stored

    def extend(self, events: Iterable[dict]) -> None:
        for e in events:
            self.append(e)

    def latest_event_id(self) -> str | None:
        return self.events[-1]["event_id"] if self.events else None

    def to_jsonl(self) -> str:
        return "\n".join(json.dumps(e, ensure_ascii=False) for e in self.events)

    @classmethod
    def from_jsonl(cls, text: str) -> "LedgerStore":
        store = cls()
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            store.append(json.loads(line))
        return store
# === END CANONICAL MODULE: ledger.py ===

# === BEGIN CANONICAL MODULE: state_projection.py ===
from typing import Iterable


GATE_ORDER = [
    "G00",
    "G10",
    "G20",
    "G30",
    "G40",
    "G50",
    "G60",
    "G60.USER",
    "G70",
    "G80",
    "G90",
]


class StateLedgerMismatch(Exception):
    """Raised when a candidate manual_gate_state.json disagrees with the
    projection rebuilt from the ledger."""

    def __init__(self, field_name: str, ledger_value, candidate_value):
        super().__init__(
            f"STATE_LEDGER_MISMATCH field={field_name} "
            f"ledger={ledger_value!r} candidate={candidate_value!r}"
        )
        self.field_name = field_name
        self.ledger_value = ledger_value
        self.candidate_value = candidate_value


def _gate_index(gate: str | None) -> int:
    if gate is None:
        return -1
    if gate not in GATE_ORDER:
        return -1
    return GATE_ORDER.index(gate)


def rebuild_state(events: Iterable[dict]) -> dict:
    """Project the current manual_gate_state.json from a ledger event list.

    The projection captures:
    - episode_id, lane, content_profile, production_mode, requested_target
      (locked at WORKFLOW_CREATED or the first G00 event).
    - current_gate / current_subgate / last_passed_gate derived from
      GATE_STARTED / GATE_PASSED / GATE_FAILED events.
    - projection_of_ledger_event_id = the last event id seen.
    """
    events = list(events)
    if not events:
        raise ValueError("STATE_REBUILD_EMPTY_LEDGER")

    genesis = events[0]
    state = {
        "schema_version": "manual-gate-state-v1",
        "episode_id": genesis.get("episode_id"),
        "lane": genesis.get("lane"),
        "content_profile": genesis.get("content_profile", "general_shorts"),
        "production_mode": genesis.get("production_mode", "not_applicable"),
        "requested_target": genesis.get("requested_target", "design_only"),
        "current_gate": None,
        "current_subgate": None,
        "last_passed_gate": None,
        "source_fingerprint": genesis.get("source_fingerprint", ""),
        "current_authoritative_artifact": None,
        "current_authoritative_sha256": None,
        "next_user_action": None,
        "auto_external_call": False,
        "release_allowed": False,
        "projection_of_ledger_event_id": genesis.get("event_id"),
        "contract_mode": genesis.get("contract_mode", "V2_CANONICAL"),
    }

    last_passed_idx = -1
    final_qc_passed = False
    for ev in events:
        et = ev.get("event_type")
        gate = ev.get("gate")
        actor = ev.get("actor")
        if et == "WORKFLOW_CREATED":
            # Promote any G00-scoped fields locked at creation.
            for k in (
                "content_profile",
                "production_mode",
                "requested_target",
                "source_fingerprint",
            ):
                if k in ev:
                    state[k] = ev[k]
        if et == "GATE_STARTED" and gate is not None:
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
        elif et == "GATE_PASSED" and gate is not None:
            idx = _gate_index(gate)
            if idx > last_passed_idx:
                last_passed_idx = idx
                state["last_passed_gate"] = gate
            # After a pass, the current gate stays at the passed gate until
            # the next GATE_STARTED event arrives.
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
            if ev.get("artifact_path"):
                state["current_authoritative_artifact"] = ev["artifact_path"]
            if ev.get("artifact_sha256"):
                state["current_authoritative_sha256"] = ev["artifact_sha256"]
        elif et == "GATE_FAILED" and gate is not None:
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
        elif et == "OWNER_TRANSFERRED":
            state["next_user_action"] = None
        elif et == "USER_VISUAL_PASS":
            state["next_user_action"] = None
        elif et == "FINAL_QC_PASS":
            # RW-P03-02 strict: FINAL_QC_PASS counts toward release only when
            # it occurs on gate=G90 and actor=VALIDATOR. A FINAL_QC_PASS
            # recorded against any other gate (e.g. G20) or any other actor
            # does not satisfy the release precondition.
            if gate == "G90" and actor == "VALIDATOR":
                final_qc_passed = True
        elif et == "UPLOAD_APPROVED":
            # RW-P03-02 strict: UPLOAD_APPROVED releases only when (a) a
            # valid G90 FINAL_QC_PASS preceded it, (b) this UPLOAD_APPROVED
            # is itself on gate=G90, and (c) its actor is USER (material
            # user-owned decision; never auto-released by RUNNER/VALIDATOR).
            if (
                final_qc_passed
                and gate == "G90"
                and actor == "USER"
            ):
                state["release_allowed"] = True
        state["projection_of_ledger_event_id"] = ev.get("event_id")

    return state


# Fields that must match exactly between a candidate state file and the
# ledger projection. Other fields (e.g. display timestamps) are advisory.
_MATCHED_FIELDS = (
    "episode_id",
    "lane",
    "content_profile",
    "production_mode",
    "current_gate",
    "current_subgate",
    "last_passed_gate",
    "current_authoritative_artifact",
    "current_authoritative_sha256",
    "projection_of_ledger_event_id",
    "release_allowed",
)


def compare_and_assert(ledger_projection: dict, candidate: dict) -> None:
    """Raise StateLedgerMismatch if the candidate state disagrees with the
    ledger projection on any matched field."""
    for field_name in _MATCHED_FIELDS:
        ledger_value = ledger_projection.get(field_name)
        candidate_value = candidate.get(field_name)
        if ledger_value != candidate_value:
            raise StateLedgerMismatch(field_name, ledger_value, candidate_value)
# === END CANONICAL MODULE: state_projection.py ===

# === BEGIN CANONICAL MODULE: gate_validation.py ===
SCHEMA_VERSION = "gate-result-v1"

ALLOWED_AUTO_ADVANCE_CLASSES = {
    "NONE",
    "DETERMINISTIC_ONLY",
    "LLM_CALL_FORBIDDEN",
    "PAID_ACTION_FORBIDDEN",
    "UPLOAD_FORBIDDEN",
}

# Any class value outside the allowed set is treated as a forbidden attempt
# to authorize automatic LLM / paid / upload work.
FORBIDDEN_AUTO_ADVANCE_CLASSES = {
    "LLM_CALL_ALLOWED",
    "PAID_ACTION_ALLOWED",
    "UPLOAD_ALLOWED",
}


class ForbiddenAdvanceClass(Exception):
    """Raised when a validator result asks the runner to perform automatic
    LLM / paid / upload work — which the validator is never allowed to do."""

    def __init__(self, auto_advance_class: str):
        super().__init__(
            f"FORBIDDEN_ADVANCE_CLASS auto_advance_class={auto_advance_class}"
        )
        self.auto_advance_class = auto_advance_class


class PassWithErrorsForbidden(Exception):
    """Raised when a caller asks validate_gate to emit PASS while the errors
    list is non-empty. PASS is the deterministic validator's positive verdict
    and must never coexist with recorded errors."""

    def __init__(self):
        super().__init__(
            "PASS_WITH_ERRORS_FORBIDDEN: status=PASS requires empty errors"
        )


def validate_gate(
    *,
    lane: str,
    gate: str,
    subgate: str | None,
    validated_inputs: list[dict],
    evidence: list[dict],
    errors: list[dict],
    warnings: list[dict],
    next_action: str,
    auto_advance_allowed: bool,
    auto_advance_class: str,
    status: str | None = None,
    reason_code: str | None = None,
) -> dict:
    """Construct a gate_result document.

    The validator itself never executes any next action; the runner does.
    The runner must reject any result whose auto_advance_class requests
    automatic LLM, paid, or upload work.

    Authority rule: if `errors` is non-empty the status can never be PASS.
    An explicit status=PASS with non-empty errors raises
    PassWithErrorsForbidden. When status is None, it is derived as FAIL
    when errors exist and PASS otherwise.
    """
    if auto_advance_class in FORBIDDEN_AUTO_ADVANCE_CLASSES:
        raise ForbiddenAdvanceClass(auto_advance_class)
    if auto_advance_class not in ALLOWED_AUTO_ADVANCE_CLASSES:
        raise ForbiddenAdvanceClass(auto_advance_class)

    has_errors = bool(errors)
    if status == "PASS" and has_errors:
        raise PassWithErrorsForbidden()

    derived_status = status
    if derived_status is None:
        derived_status = "FAIL" if has_errors else "PASS"

    result = {
        "schema_version": SCHEMA_VERSION,
        "status": derived_status,
        "reason_code": reason_code,
        "lane": lane,
        "gate": gate,
        "subgate": subgate,
        "validated_inputs": list(validated_inputs),
        "evidence": list(evidence),
        "errors": list(errors),
        "warnings": list(warnings),
        "next_action": next_action,
        "auto_advance_allowed": bool(auto_advance_allowed),
        "auto_advance_class": auto_advance_class,
    }
    return result
# === END CANONICAL MODULE: gate_validation.py ===

# === BEGIN CANONICAL MODULE: cost_guard.py ===
from dataclasses import dataclass


class CostOverrun(Exception):
    """Raised when a paid action would exceed the configured budget."""

    def __init__(self, kind: str, requested, limit):
        super().__init__(
            f"COST_OVERRUN kind={kind} requested={requested} limit={limit}"
        )
        self.kind = kind
        self.requested = requested
        self.limit = limit


@dataclass
class CostGuard:
    episode_budget_usd: float | None
    max_model_input_tokens_per_gate: int | None
    max_model_output_tokens_per_gate: int | None
    max_paid_tts_chars: int | None
    paid_tts_authorization: dict
    spent_tts_chars: int = 0
    spent_model_input_tokens: int = 0
    spent_model_output_tokens: int = 0
    spent_usd: float = 0.0

    def can_authorize_paid_action(self) -> bool:
        """A paid action requires both a non-zero episode budget AND an
        explicit authorization scope. No budget => no paid action."""
        if self.episode_budget_usd is None or self.episode_budget_usd <= 0:
            return False
        status = self.paid_tts_authorization.get("status")
        scope = self.paid_tts_authorization.get("scope")
        if status != "AUTHORIZED_FOR_EPISODE":
            return False
        if scope in (None, "none"):
            return False
        return True

    def can_spend_tts(self, *, chars: int) -> bool:
        """Check whether a paid TTS spend of `chars` fits within both the
        authorization limit and the episode budget."""
        if chars < 0:
            return False
        if not self.can_authorize_paid_action():
            return False
        limit = self.paid_tts_authorization.get("max_chars")
        if limit is not None and self.spent_tts_chars + chars > limit:
            return False
        if (
            self.max_paid_tts_chars is not None
            and self.spent_tts_chars + chars > self.max_paid_tts_chars
        ):
            return False
        return True

    def record_tts_spend(self, *, chars: int) -> None:
        if not self.can_spend_tts(chars=chars):
            raise CostOverrun("tts_chars", chars, self.max_paid_tts_chars)
        self.spent_tts_chars += chars

    def can_spend_model_tokens(self, *, input_tokens: int, output_tokens: int) -> bool:
        if self.max_model_input_tokens_per_gate is not None:
            if self.spent_model_input_tokens + input_tokens > self.max_model_input_tokens_per_gate:
                return False
        if self.max_model_output_tokens_per_gate is not None:
            if self.spent_model_output_tokens + output_tokens > self.max_model_output_tokens_per_gate:
                return False
        return True
# === END CANONICAL MODULE: cost_guard.py ===

# === BEGIN CANONICAL MODULE: context_manifest.py ===
import hashlib
from dataclasses import dataclass, field


SCHEMA_VERSION = "context-manifest-v1"

DEFAULT_ESTIMATOR_VERSION = "chars_div_4_v1"


@dataclass
class ContextManifest:
    lane: str
    gate: str
    subgate: str | None
    run_id: str
    loaded_files: list[dict] = field(default_factory=list)
    excluded_by_policy: list[str] = field(default_factory=list)
    provider_input_tokens: int | None = None
    estimated_input_tokens: int | None = None
    estimator_version: str = DEFAULT_ESTIMATOR_VERSION
    unrelated_lane_reads: int = 0
    legacy_reads: int = 0
    full_srt_injected: bool = False
    contract_mode: str = "V2_CANONICAL"
    status: str = "PASS"

    def add_loaded_file(self, path: str, content: bytes | str | None = None) -> None:
        entry = {"path": path}
        if content is not None:
            if isinstance(content, str):
                content = content.encode("utf-8")
            entry["sha256"] = hashlib.sha256(content).hexdigest().upper()
            entry["chars"] = len(content)
        self.loaded_files.append(entry)

    def add_excluded(self, category: str) -> None:
        if category not in self.excluded_by_policy:
            self.excluded_by_policy.append(category)

    def set_estimated_tokens_from_chars(self, total_chars: int) -> None:
        # Simple deterministic estimator; production may override.
        self.estimated_input_tokens = max(0, total_chars // 4)
        self.estimator_version = DEFAULT_ESTIMATOR_VERSION

    def to_dict(self) -> dict:
        if self.provider_input_tokens is None and self.estimated_input_tokens is None:
            raise ValueError(
                "CONTEXT_MANIFEST_MISSING_TOKENS: set provider_input_tokens "
                "or estimated_input_tokens"
            )
        return {
            "schema_version": SCHEMA_VERSION,
            "lane": self.lane,
            "gate": self.gate,
            "subgate": self.subgate,
            "run_id": self.run_id,
            "loaded_files": list(self.loaded_files),
            "excluded_by_policy": list(self.excluded_by_policy),
            "provider_input_tokens": self.provider_input_tokens,
            "estimated_input_tokens": self.estimated_input_tokens,
            "estimator_version": self.estimator_version
            if self.provider_input_tokens is None
            else None,
            "unrelated_lane_reads": self.unrelated_lane_reads,
            "legacy_reads": self.legacy_reads,
            "full_srt_injected": self.full_srt_injected,
            "contract_mode": self.contract_mode,
            "status": self.status,
        }
# === END CANONICAL MODULE: context_manifest.py ===

# === BEGIN CANONICAL MODULE: canonical_render.py ===
import hashlib
import json
from typing import Any


class HumanMdCanonicalJsonMismatch(Exception):
    def __init__(self, kind: str, detail: str):
        super().__init__(f"HUMAN_MD_CANONICAL_JSON_MISMATCH kind={kind} {detail}")
        self.kind = kind
        self.detail = detail


RECORD_PREFIX = "R "


def _hash_canonical(canonical: Any) -> str:
    return hashlib.sha256(
        json.dumps(canonical, sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest().upper()


def _collect_records(
    value: Any,
    segments: list[str] | None = None,
) -> list[tuple[list[str], Any]]:
    """Walk canonical recursively and return [(segments, value)] for every
    scalar leaf plus explicit markers for empty containers.

    Containers (dict / non-empty list) produce no record of their own but
    their children carry the parent segments. Empty containers emit a
    synthetic record so adding/removing them is detectable.

    ``segments`` is a list of string segment names. Dict keys are appended
    verbatim (a key may contain dots; that's fine because we never split
    on dots — we transport the whole array). List indices are appended as
    ``[i]`` strings to mirror the source structure.
    """
    if segments is None:
        segments = []
    out: list[tuple[list[str], Any]] = []
    if isinstance(value, dict):
        if not value:
            out.append((list(segments), {"__empty__": "object"}))
            return out
        for k in sorted(value.keys()):
            child = list(segments)
            child.append(str(k))
            out.extend(_collect_records(value[k], child))
        return out
    if isinstance(value, list):
        if not value:
            out.append((list(segments), {"__empty__": "list"}))
            return out
        for i, item in enumerate(value):
            child = list(segments)
            child.append(f"[{i}]")
            out.extend(_collect_records(item, child))
        return out
    # Scalar leaf — keep the original Python value so json.dumps preserves
    # the JSON type exactly (bool vs number vs string).
    out.append((list(segments), value))
    return out


def _serialize_record(segments: list[str], value: Any) -> str:
    """Encode one record as a single JSON array line."""
    return RECORD_PREFIX + json.dumps([segments, value], ensure_ascii=False)


def _parse_record_line(line: str) -> tuple[list[str], Any] | None:
    """Parse a single record line. Returns (segments, value) or None if
    the line is not a record line."""
    s = line.strip()
    if not s.startswith(RECORD_PREFIX):
        return None
    payload = s[len(RECORD_PREFIX):]
    try:
        rec = json.loads(payload)
    except json.JSONDecodeError:
        return None
    if not isinstance(rec, list) or len(rec) != 2:
        return None
    segments, value = rec
    if not isinstance(segments, list) or not all(
        isinstance(x, str) for x in segments
    ):
        return None
    return segments, value


def _parse_records_from_md(md: str) -> list[tuple[list[str], Any]]:
    """Parse every record line in the MD, preserving multiplicity and order."""
    out: list[tuple[list[str], Any]] = []
    for raw in md.splitlines():
        rec = _parse_record_line(raw)
        if rec is not None:
            out.append(rec)
    return out


def render_markdown(canonical: Any) -> str:
    """Render canonical JSON to deterministic markdown with lossless record
    encoding."""
    # Round-trip through json for deterministic key ordering and to reject
    # non-JSON-serializable input early.
    serialized = json.dumps(canonical, sort_keys=True, ensure_ascii=False)
    canonical_norm = json.loads(serialized)
    sha = _hash_canonical(canonical_norm)

    records = _collect_records(canonical_norm)
    # Sort records by (segments, json(value)) for deterministic output that
    # is independent of insertion order.
    records.sort(key=lambda r: (r[0], json.dumps(r[1], sort_keys=True, ensure_ascii=False)))

    title = (
        canonical_norm.get("schema_version")
        if isinstance(canonical_norm, dict)
        else None
    ) or "canonical-json"

    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("<!-- Rendered from canonical JSON. Do not edit. -->")
    lines.append("<!-- Each 'R ' line below is one JSON record [segments, value].")
    lines.append("     Reconciliation parses those records and compares them")
    lines.append("     losslessly as a sorted, multiplicity-preserving list. -->")
    lines.append("")
    lines.append("## Records")
    lines.append("")
    for segments, value in records:
        lines.append(_serialize_record(segments, value))
    lines.append("")
    lines.append(f"<!-- CANONICAL_SHA256: {sha} -->")
    lines.append("")
    return "\n".join(lines)


def reconcile_human_md(*, canonical: Any, human_md: str) -> dict:
    """Compare a hand-edited MD against the canonical JSON projection.

    Strategy (RW-P04-03 round 5, lossless codec):
    - Build the canonical record list (segments, value) preserving type
      and multiplicity.
    - Parse the human MD's R-lines into the same shape.
    - Sort both lists (canonical key for sorted order) and compare element
      by element. Set semantics are explicitly forbidden: duplicate lines
      and structural collisions must be caught.

    Outcomes:
    - IN_SYNC: the human MD is byte-identical to a fresh canonical render.
    - COSMETIC_DIFF_ONLY: the record lists are identical (same scalars,
      same multiplicity) but the surrounding MD text differs.
    - HumanMdCanonicalJsonMismatch: the record lists differ.
    """
    canonical_norm = json.loads(
        json.dumps(canonical, sort_keys=True, ensure_ascii=False)
    )
    canonical_records = _collect_records(canonical_norm)
    human_records = _parse_records_from_md(human_md)

    # Sort key: deterministic ordering independent of source order. Segments
    # are converted to tuples so the key is hashable for the Counter step.
    def _key(rec: tuple[list[str], Any]) -> tuple:
        segments, value = rec
        return (tuple(segments), json.dumps(value, sort_keys=True, ensure_ascii=False))

    canonical_sorted = sorted(canonical_records, key=_key)
    human_sorted = sorted(human_records, key=_key)

    if canonical_sorted == human_sorted:
        # Record lists identical. Now decide IN_SYNC vs COSMETIC_DIFF_ONLY
        # by comparing the surrounding MD text against a fresh render.
        fresh = render_markdown(canonical)
        if human_md.strip() == fresh.strip():
            return {"status": "IN_SYNC", "action": "NONE"}
        return {"status": "COSMETIC_DIFF_ONLY", "action": "RE_RENDER_RECOMMENDED"}

    # Record lists differ. Classify the difference for the error message.
    canonical_count: dict[tuple, int] = {}
    for rec in canonical_sorted:
        k = _key(rec)
        canonical_count[k] = canonical_count.get(k, 0) + 1
    human_count: dict[tuple, int] = {}
    for rec in human_sorted:
        k = _key(rec)
        human_count[k] = human_count.get(k, 0) + 1

    missing = [
        k for k, n in canonical_count.items() if human_count.get(k, 0) < n
    ]
    extra = [
        k for k, n in human_count.items() if canonical_count.get(k, 0) < n
    ]
    # Render a short readable preview of the first few diffs.
    def _preview(key_tuple: tuple) -> str:
        segments_tuple, value_json = key_tuple
        path = "/".join(segments_tuple) if segments_tuple else "<root>"
        return f"{path}={value_json}"

    detail = (
        f"missing_or_underrepresented={[ _preview(k) for k in missing[:5] ]} "
        f"extra_or_overrepresented={[ _preview(k) for k in extra[:5] ]} "
        f"(canonical_records={len(canonical_sorted)} "
        f"human_records={len(human_sorted)})"
    )
    raise HumanMdCanonicalJsonMismatch("STRUCTURAL_OR_VALUE_CHANGE", detail)
# === END CANONICAL MODULE: canonical_render.py ===

# === BEGIN CANONICAL MODULE: prompt_factory.py ===
import hashlib
import json
from dataclasses import dataclass, field
from typing import Any


PROMPT_MANIFEST_SCHEMA_VERSION = "prompt-packet-manifest-v1"
ANALYSIS_CACHE_SCHEMA_VERSION = "analysis-cache-manifest-v1"


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest().upper()


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest().upper()


# ---------------------------------------------------------------------------
# Prompt Factory
# ---------------------------------------------------------------------------


def _content_address_key(
    *,
    template_sha256: str,
    input_artifacts: list[dict],
    included_segment_ids: list[str],
    excluded_fields: list[str],
    language_quality_contract_sha: str,
    external_authority_contract_sha: str,
) -> str:
    """Stable content-addressed key for prompt-packet reuse."""
    payload = json.dumps(
        {
            "template_sha256": template_sha256,
            "input_artifacts": [
                {"path": a["path"], "sha256": a["sha256"]} for a in input_artifacts
            ],
            "included_segment_ids": list(included_segment_ids),
            "excluded_fields": sorted(excluded_fields),
            "language_quality_contract_sha256": language_quality_contract_sha,
            "external_authority_contract_sha256": external_authority_contract_sha,
        },
        sort_keys=True,
        ensure_ascii=False,
    )
    return _sha256_text(payload)


def build_prompt(
    *,
    template_path: str,
    template_text: str,
    inputs: list[dict],
    included_segment_ids: list[str],
    excluded_fields: list[str],
    language_quality_contract: str,
    external_authority_contract: str,
) -> dict:
    """Build an external prompt packet + manifest.

    inputs: list of {path, content} dicts. Content may be str or bytes.
    The packet body is deterministic: template, then inputs in given order,
    then the shared contracts appended.

    The manifest records the content-addressed packet SHA so callers can
    reuse the same packet when the key matches.
    """
    if not isinstance(template_text, str):
        raise TypeError("template_text must be str")
    template_sha = _sha256_text(template_text)

    input_artifacts: list[dict] = []
    input_bodies: list[str] = []
    for inp in inputs:
        path = inp["path"]
        content = inp["content"]
        if isinstance(content, str):
            content_bytes = content.encode("utf-8")
        elif isinstance(content, (bytes, bytearray)):
            content_bytes = bytes(content)
        else:
            raise TypeError(f"input content must be str or bytes: {path}")
        sha = _sha256_bytes(content_bytes)
        input_artifacts.append({"path": path, "sha256": sha})
        input_bodies.append(
            f"--- INPUT: {path} (sha256={sha}) ---\n{content_bytes.decode('utf-8', errors='replace')}"
        )

    lq_text = ""
    lq_sha = ""
    if language_quality_contract:
        try:
            from pathlib import Path

            lq_text = Path(language_quality_contract).read_text(encoding="utf-8")
            lq_sha = _sha256_text(lq_text)
        except OSError:
            lq_text = ""
            lq_sha = ""

    ea_text = ""
    ea_sha = ""
    if external_authority_contract:
        try:
            from pathlib import Path

            ea_text = Path(external_authority_contract).read_text(encoding="utf-8")
            ea_sha = _sha256_text(ea_text)
        except OSError:
            ea_text = ""
            ea_sha = ""

    # Compose the packet in a fixed order.
    parts: list[str] = []
    parts.append("# External Prompt Packet")
    parts.append("")
    parts.append(f"<!-- template_path: {template_path} -->")
    parts.append(f"<!-- template_sha256: {template_sha} -->")
    parts.append("")
    parts.append("## Template")
    parts.append("")
    parts.append(template_text.strip())
    parts.append("")
    if included_segment_ids:
        parts.append("## Included Segment IDs")
        parts.append("")
        for sid in included_segment_ids:
            parts.append(f"- {sid}")
        parts.append("")
    if excluded_fields:
        parts.append("## Excluded Fields (do not surface to external model)")
        parts.append("")
        for f in excluded_fields:
            parts.append(f"- {f}")
        parts.append("")
    parts.append("## Inputs")
    parts.append("")
    parts.extend(input_bodies)
    parts.append("")
    if lq_text:
        parts.append("## Shared Language Quality Contract")
        parts.append("")
        parts.append(lq_text.strip())
        parts.append("")
    if ea_text:
        parts.append("## Shared External Authority Contract")
        parts.append("")
        parts.append(ea_text.strip())
        parts.append("")

    packet_text = "\n".join(parts)
    packet_sha = _sha256_text(packet_text)

    content_key = _content_address_key(
        template_sha256=template_sha,
        input_artifacts=input_artifacts,
        included_segment_ids=included_segment_ids,
        excluded_fields=excluded_fields,
        language_quality_contract_sha=lq_sha,
        external_authority_contract_sha=ea_sha,
    )

    manifest = {
        "schema_version": PROMPT_MANIFEST_SCHEMA_VERSION,
        "template_path": template_path,
        "template_sha256": template_sha,
        "language_quality_contract_path": language_quality_contract or None,
        "language_quality_contract_sha256": lq_sha or None,
        "external_authority_contract_path": external_authority_contract or None,
        "external_authority_contract_sha256": ea_sha or None,
        "input_artifacts": input_artifacts,
        "included_segment_ids": list(included_segment_ids),
        "excluded_fields": list(excluded_fields),
        "content_addressed_key": content_key,
        "packet_sha256": packet_sha,
        "packet_text": packet_text,
    }
    return {"packet_text": packet_text, "manifest": manifest}


# ---------------------------------------------------------------------------
# Analysis cache
# ---------------------------------------------------------------------------


@dataclass
class _LayerInputs:
    """Which upstream inputs each cache layer depends on. Used by the
    invalidation planner to invalidate only the affected layer."""

    transcript_segments: tuple[str, ...] = ("source_sha256",)
    ocr_segments: tuple[str, ...] = ("source_sha256", "tool_versions.ocr")
    scene_segments: tuple[str, ...] = (
        "source_sha256",
        "tool_versions.scene",
        "sampling_policy.frame_sample_fps",
    )
    motion_segments: tuple[str, ...] = (
        "source_sha256",
        "tool_versions.scene",
        "sampling_policy.frame_sample_fps",
    )
    speaker_segments: tuple[str, ...] = ("source_sha256",)
    audio_event_segments: tuple[str, ...] = ("source_sha256",)


_LAYER_DEPS = _LayerInputs()


def _layer_depends_on(layer_name: str) -> tuple[str, ...]:
    return getattr(_LAYER_DEPS, layer_name, ("source_sha256",))


def _cache_key_payload(
    *,
    source_sha256: str,
    duration_us: int,
    resolution: str,
    selected_range: dict,
    profile_version: str,
    tool_versions: dict,
    sampling_policy: dict,
) -> str:
    return json.dumps(
        {
            "source_sha256": source_sha256,
            "duration_us": duration_us,
            "resolution": resolution,
            "selected_range": selected_range,
            "profile_version": profile_version,
            "tool_versions": tool_versions,
            "sampling_policy": sampling_policy,
        },
        sort_keys=True,
        ensure_ascii=False,
    )


def build_analysis_cache_manifest(
    *,
    source_sha256: str,
    duration_us: int,
    resolution: str,
    selected_range: dict,
    profile_version: str,
    tool_versions: dict,
    sampling_policy: dict,
    layers: dict,
    external_analysis: dict | None = None,
) -> dict:
    """Build an analysis-cache manifest.

    external_analysis, when provided, is treated as optional supplementary
    input. If it disagrees with local primary evidence on a tracked hash
    (e.g. transcript_sha256), the manifest records
    external_analysis_status=EXTERNAL_ANALYSIS_MISMATCH and does NOT adopt
    the external result.
    """
    if not isinstance(layers, dict) or not layers:
        raise ValueError("ANALYSIS_CACHE_EMPTY_LAYERS")
    for layer_name, layer in layers.items():
        if "sha256" not in layer:
            raise ValueError(f"ANALYSIS_CACHE_LAYER_MISSING_SHA: {layer_name}")

    key = _sha256_text(
        _cache_key_payload(
            source_sha256=source_sha256,
            duration_us=duration_us,
            resolution=resolution,
            selected_range=selected_range,
            profile_version=profile_version,
            tool_versions=tool_versions,
            sampling_policy=sampling_policy,
        )
    )

    external_status = "NOT_PROVIDED"
    if external_analysis is not None:
        # Compare any tracked hash the external result claims against the
        # local layer hash of the same name.
        external_status = "ACCEPTED_SUPPLEMENTARY"
        for ext_key, local_layer in (
            ("transcript_sha256", "transcript_segments"),
            ("ocr_sha256", "ocr_segments"),
            ("scene_sha256", "scene_segments"),
        ):
            if ext_key in external_analysis and local_layer in layers:
                if external_analysis[ext_key] != layers[local_layer]["sha256"]:
                    external_status = "EXTERNAL_ANALYSIS_MISMATCH"
                    break

    return {
        "schema_version": ANALYSIS_CACHE_SCHEMA_VERSION,
        "cache_key_sha256": key,
        "source_sha256": source_sha256,
        "duration_us": duration_us,
        "resolution": resolution,
        "selected_range": selected_range,
        "profile_version": profile_version,
        "tool_versions": dict(tool_versions),
        "sampling_policy": dict(sampling_policy),
        "layers": dict(layers),
        "external_analysis": external_analysis,
        "external_analysis_status": external_status,
    }


def plan_cache_invalidation(
    *,
    current_manifest: dict,
    new_inputs: dict,
) -> dict:
    """Decide which layers to invalidate when inputs change.

    Cache-key components (all trigger full invalidation when changed):
    - source_sha256
    - duration_us
    - resolution
    - selected_range
    - profile_version

    Per-layer inputs (trigger only dependent layers):
    - tool_versions.<x>
    - sampling_policy.<key>

    RW-P04-02: every cache-key component change must invalidate all layers,
    because the cache key itself is no longer valid.
    """
    current_source = current_manifest.get("source_sha256")
    new_source = new_inputs.get("source_sha256")
    if current_source != new_source:
        return {
            "invalidate": sorted(current_manifest.get("layers", {}).keys()),
            "reason": "SOURCE_SHA256_CHANGED",
        }

    # Any cache-key component change invalidates every layer (the cache key
    # itself changed, so no cached layer is reusable).
    cache_key_fields = ("duration_us", "resolution", "selected_range", "profile_version")
    for field in cache_key_fields:
        if current_manifest.get(field) != new_inputs.get(field):
            return {
                "invalidate": sorted(current_manifest.get("layers", {}).keys()),
                "reason": f"CACHE_KEY_FIELD_CHANGED:{field}",
            }

    invalidate: set[str] = set()
    current_tools = current_manifest.get("tool_versions", {})
    new_tools = new_inputs.get("tool_versions", {})
    current_sampling = current_manifest.get("sampling_policy", {})
    new_sampling = new_inputs.get("sampling_policy", {})

    sampling_changed = current_sampling != new_sampling

    for layer_name in current_manifest.get("layers", {}).keys():
        deps = _layer_depends_on(layer_name)
        for dep in deps:
            if dep == "source_sha256":
                continue
            if dep.startswith("tool_versions."):
                tool_key = dep.split(".", 1)[1]
                if current_tools.get(tool_key) != new_tools.get(tool_key):
                    invalidate.add(layer_name)
                    break
            elif dep.startswith("sampling_policy."):
                if sampling_changed:
                    invalidate.add(layer_name)
                    break

    return {
        "invalidate": sorted(invalidate),
        "reason": "PARTIAL_INVALIDATION",
    }
# === END CANONICAL MODULE: prompt_factory.py ===


# WORKFLOW_HARNESS_SOURCE_VERSION = 'shared-gates-separated-lanes-v2'
# WORKFLOW_HARNESS_SOURCE_SHA256 = '0D8D362A4AF320D746018094BAF860C697FB212703BCC2388883CC508F6A353E'
# DO NOT EDIT — regenerate via scripts/sync_shared_workflow_harness.py
