"""Deterministically regenerate the vendored workflow harness core.

The canonical source lives at shared/workflow-harness/core/*.py. Each of the
three production skills receives a byte-identical vendored copy at:

    skills/<skill>/scripts/_generated/workflow_harness_core.py
    skills/<skill>/scripts/_generated/WORKFLOW_HARNESS_VERSION

The generated file is a single self-contained Python module that exposes the
same public API as the canonical core. It is regenerated from the canonical
source by textual concatenation in a fixed module order, with a header that
records the source version and aggregate SHA-256.

Generated files are NOT manually edited. NORM-008.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SHARED_CORE_DIR = REPO_ROOT / "shared" / "workflow-harness" / "core"
SHARED_VERSION_FILE = REPO_ROOT / "shared" / "workflow-harness" / "VERSION"

# Fixed module order so the generated file is deterministic. The order is
# dependency-ordered: low-level utilities first, then dependents.
CORE_MODULE_ORDER = [
    "ledger.py",
    "state_projection.py",
    "legacy_compat.py",
    "gate_validation.py",
    "cost_guard.py",
    "context_manifest.py",
    "runner_policy.py",
    "effect_policy.py",
    "canonical_render.py",
    "prompt_factory.py",
]

TARGET_SKILLS = [
    "00-tikitaka",
    "000short-production-agent",
    "111-politics-longform",
]


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _strip_module_header(text: str) -> str:
    """Strip leading module docstring AND `from __future__ import annotations`
    so the generated bundle does not carry:
    - five stacked top-of-file docstrings
    - five `from __future__ import annotations` lines (which Python forbids:
      future imports must occur only at the beginning of a file).

    The bundle emits its own single `from __future__ import annotations` at
    the top. Per-module future imports are removed here.
    """
    stripped = text.lstrip()
    if stripped.startswith('"""'):
        end = stripped.find('"""', 3)
        if end != -1:
            stripped = stripped[end + 3 :].lstrip()
    # Remove any `from __future__ import ...` lines anywhere in the module
    # body. The bundle emits one at the top; per-module copies are illegal
    # mid-file.
    lines = stripped.splitlines()
    filtered = [
        line for line in lines
        if not line.strip().startswith("from __future__ import")
    ]
    return "\n".join(filtered).strip()


def build_canonical_bundle() -> tuple[str, str, str]:
    """Return (bundle_text, source_version, source_sha256)."""
    source_version = _read(SHARED_VERSION_FILE).strip()
    parts: list[str] = []
    parts.append(
        '"""AUTO-GENERATED by scripts/sync_shared_workflow_harness.py.\n\n'
        "DO NOT EDIT. This file is a byte-identical vendored copy of the\n"
        "canonical shared/workflow-harness/core modules. Edit the canonical\n"
        "source and re-run sync_shared_workflow_harness.py.\n\n"
        f"WORKFLOW_HARNESS_SOURCE_VERSION: {source_version}\n"
        '"""'
    )
    parts.append("from __future__ import annotations\n")
    aggregate = hashlib.sha256()
    for name in CORE_MODULE_ORDER:
        path = SHARED_CORE_DIR / name
        raw = _read(path)
        aggregate.update(raw.encode("utf-8"))
        body = _strip_module_header(raw)
        parts.append(f"# === BEGIN CANONICAL MODULE: {name} ===")
        parts.append(body.rstrip())
        parts.append(f"# === END CANONICAL MODULE: {name} ===\n")
    source_sha256 = aggregate.hexdigest().upper()
    header = (
        f"\n# WORKFLOW_HARNESS_SOURCE_VERSION = {source_version!r}\n"
        f"# WORKFLOW_HARNESS_SOURCE_SHA256 = {source_sha256!r}\n"
        "# DO NOT EDIT — regenerate via scripts/sync_shared_workflow_harness.py"
    )
    parts.append(header)
    bundle = "\n".join(parts) + "\n"
    return bundle, source_version, source_sha256


def sync_all(repo_root: Path | None = None) -> dict:
    root = Path(repo_root) if repo_root else REPO_ROOT
    bundle, version, source_sha = build_canonical_bundle()
    skills_root = root / "skills"
    written: list[str] = []
    for skill in TARGET_SKILLS:
        target_dir = skills_root / skill / "scripts" / "_generated"
        target_dir.mkdir(parents=True, exist_ok=True)
        core_path = target_dir / "workflow_harness_core.py"
        version_path = target_dir / "WORKFLOW_HARNESS_VERSION"
        core_path.write_text(bundle, encoding="utf-8")
        version_path.write_text(version + "\n", encoding="utf-8")
        written.append(str(core_path))
    return {
        "status": "PASS",
        "source_version": version,
        "source_sha256": source_sha,
        "written": written,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the vendored workflow harness core in each skill."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=REPO_ROOT,
        help="Repository root (defaults to the parent of this script).",
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Do not write; exit non-zero if generated copies are stale.",
    )
    args = parser.parse_args(argv)

    bundle, version, source_sha = build_canonical_bundle()
    if args.check_only:
        skills_root = args.repo_root / "skills"
        stale = []
        for skill in TARGET_SKILLS:
            core_path = skills_root / skill / "scripts" / "_generated" / "workflow_harness_core.py"
            if not core_path.exists():
                stale.append(f"{skill}: missing")
                continue
            if core_path.read_text(encoding="utf-8") != bundle:
                stale.append(f"{skill}: stale")
        if stale:
            print("STALE")
            for s in stale:
                print(" ", s)
            return 1
        print("UP_TO_DATE")
        return 0

    result = sync_all(repo_root=args.repo_root)
    print(f"SYNC PASS version={result['source_version']} sha={result['source_sha256'][:16]}")
    for path in result["written"]:
        print(f"  wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
