"""AUTO-GENERATED by scripts/sync_shared_workflow_harness.py.

DO NOT EDIT. This file is a byte-identical vendored copy of the
canonical shared/workflow-harness/core modules. Edit the canonical
source and re-run sync_shared_workflow_harness.py.

WORKFLOW_HARNESS_SOURCE_VERSION: shared-gates-separated-lanes-v2
"""
from __future__ import annotations

# === BEGIN CANONICAL MODULE: ledger.py ===
import json
from dataclasses import dataclass, field
from typing import Iterable


class BrokenChainError(Exception):
    """Raised when an appended event references a non-existent
    previous_event_id, or when the event_id collides with an existing one."""

    def __init__(self, event_id: str, previous_event_id: str | None):
        super().__init__(
            f"BROKEN_CHAIN event_id={event_id} "
            f"previous_event_id={previous_event_id}"
        )
        self.event_id = event_id
        self.previous_event_id = previous_event_id


class DuplicateEventError(Exception):
    def __init__(self, event_id: str):
        super().__init__(f"DUPLICATE_EVENT event_id={event_id}")
        self.event_id = event_id


@dataclass
class LedgerStore:
    """In-memory append-only event log.

    Validations performed on append:
    - event_id must be unique within the store.
    - previous_event_id must reference an existing event, or be None only
      when the store is empty (genesis).
    """

    events: list[dict] = field(default_factory=list)
    _by_id: dict[str, dict] = field(default_factory=dict)

    def append(self, event: dict) -> dict:
        if not isinstance(event, dict):
            raise TypeError("ledger event must be a dict")
        event_id = event.get("event_id")
        prev = event.get("previous_event_id")
        if not event_id:
            raise BrokenChainError(None, prev)
        if event_id in self._by_id:
            raise DuplicateEventError(event_id)
        # Genesis rule: the very first event must have previous_event_id=None.
        if not self.events:
            if prev is not None:
                raise BrokenChainError(event_id, prev)
        else:
            if prev is None:
                raise BrokenChainError(event_id, None)
            if prev not in self._by_id:
                raise BrokenChainError(event_id, prev)
        # Freeze a shallow copy to avoid callers mutating history.
        stored = dict(event)
        self.events.append(stored)
        self._by_id[event_id] = stored
        return stored

    def extend(self, events: Iterable[dict]) -> None:
        for e in events:
            self.append(e)

    def latest_event_id(self) -> str | None:
        return self.events[-1]["event_id"] if self.events else None

    def to_jsonl(self) -> str:
        return "\n".join(json.dumps(e, ensure_ascii=False) for e in self.events)

    @classmethod
    def from_jsonl(cls, text: str) -> "LedgerStore":
        store = cls()
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            store.append(json.loads(line))
        return store
# === END CANONICAL MODULE: ledger.py ===

# === BEGIN CANONICAL MODULE: state_projection.py ===
from typing import Iterable


GATE_ORDER = [
    "G00",
    "G10",
    "G20",
    "G30",
    "G40",
    "G50",
    "G60",
    "G60.USER",
    "G70",
    "G80",
    "G90",
]


class StateLedgerMismatch(Exception):
    """Raised when a candidate manual_gate_state.json disagrees with the
    projection rebuilt from the ledger."""

    def __init__(self, field_name: str, ledger_value, candidate_value):
        super().__init__(
            f"STATE_LEDGER_MISMATCH field={field_name} "
            f"ledger={ledger_value!r} candidate={candidate_value!r}"
        )
        self.field_name = field_name
        self.ledger_value = ledger_value
        self.candidate_value = candidate_value


def _gate_index(gate: str | None) -> int:
    if gate is None:
        return -1
    if gate not in GATE_ORDER:
        return -1
    return GATE_ORDER.index(gate)


def rebuild_state(events: Iterable[dict]) -> dict:
    """Project the current manual_gate_state.json from a ledger event list.

    The projection captures:
    - episode_id, lane, content_profile, production_mode, requested_target
      (locked at WORKFLOW_CREATED or the first G00 event).
    - current_gate / current_subgate / last_passed_gate derived from
      GATE_STARTED / GATE_PASSED / GATE_FAILED events.
    - projection_of_ledger_event_id = the last event id seen.
    """
    events = list(events)
    if not events:
        raise ValueError("STATE_REBUILD_EMPTY_LEDGER")

    genesis = events[0]
    state = {
        "schema_version": "manual-gate-state-v1",
        "episode_id": genesis.get("episode_id"),
        "lane": genesis.get("lane"),
        "content_profile": genesis.get("content_profile", "general_shorts"),
        "production_mode": genesis.get("production_mode", "not_applicable"),
        "requested_target": genesis.get("requested_target", "design_only"),
        "current_gate": None,
        "current_subgate": None,
        "last_passed_gate": None,
        "source_fingerprint": genesis.get("source_fingerprint", ""),
        "current_authoritative_artifact": None,
        "current_authoritative_sha256": None,
        "next_user_action": None,
        "auto_external_call": False,
        "release_allowed": False,
        "projection_of_ledger_event_id": genesis.get("event_id"),
        "contract_mode": genesis.get("contract_mode", "V2_CANONICAL"),
    }

    passed_gate_indices: set[int] = set()
    last_passed_idx = -1
    final_qc_passed = False
    for ev in events:
        et = ev.get("event_type")
        gate = ev.get("gate")
        actor = ev.get("actor")
        if et == "WORKFLOW_CREATED":
            # Promote any G00-scoped fields locked at creation.
            for k in (
                "content_profile",
                "production_mode",
                "requested_target",
                "source_fingerprint",
            ):
                if k in ev:
                    state[k] = ev[k]
        if et == "GATE_STARTED" and gate is not None:
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
        elif et == "GATE_PASSED" and gate is not None:
            idx = _gate_index(gate)
            if idx >= 0:
                passed_gate_indices.add(idx)
            if idx > last_passed_idx:
                last_passed_idx = idx
                state["last_passed_gate"] = gate
            # After a pass, the current gate stays at the passed gate until
            # the next GATE_STARTED event arrives.
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
            if ev.get("artifact_path"):
                state["current_authoritative_artifact"] = ev["artifact_path"]
            if ev.get("artifact_sha256"):
                state["current_authoritative_sha256"] = ev["artifact_sha256"]
        elif et == "GATE_FAILED" and gate is not None:
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
        elif et == "LOCK_INVALIDATED" and gate is not None:
            rewind_idx = _gate_index(gate)
            if rewind_idx < 0:
                raise ValueError(f"STATE_REBUILD_INVALID_REWIND_GATE gate={gate}")
            passed_gate_indices = {
                idx for idx in passed_gate_indices if idx < rewind_idx
            }
            last_passed_idx = (
                max(passed_gate_indices) if passed_gate_indices else -1
            )
            state["last_passed_gate"] = (
                GATE_ORDER[last_passed_idx] if last_passed_idx >= 0 else None
            )
            state["current_gate"] = gate
            state["current_subgate"] = ev.get("subgate")
            state["current_authoritative_artifact"] = None
            state["current_authoritative_sha256"] = None
            state["next_user_action"] = None
            state["release_allowed"] = False
            final_qc_passed = False
        elif et == "OWNER_TRANSFERRED":
            state["next_user_action"] = None
        elif et == "USER_VISUAL_PASS":
            state["next_user_action"] = None
        elif et == "FINAL_QC_PASS":
            # RW-P03-02 strict: FINAL_QC_PASS counts toward release only when
            # it occurs on gate=G90 and actor=VALIDATOR. A FINAL_QC_PASS
            # recorded against any other gate (e.g. G20) or any other actor
            # does not satisfy the release precondition.
            if gate == "G90" and actor == "VALIDATOR":
                final_qc_passed = True
        elif et == "UPLOAD_APPROVED":
            # RW-P03-02 strict: UPLOAD_APPROVED releases only when (a) a
            # valid G90 FINAL_QC_PASS preceded it, (b) this UPLOAD_APPROVED
            # is itself on gate=G90, and (c) its actor is USER (material
            # user-owned decision; never auto-released by RUNNER/VALIDATOR).
            if (
                final_qc_passed
                and gate == "G90"
                and actor == "USER"
            ):
                state["release_allowed"] = True
        state["projection_of_ledger_event_id"] = ev.get("event_id")

    return state


# Fields that must match exactly between a candidate state file and the
# ledger projection. Other fields (e.g. display timestamps) are advisory.
_MATCHED_FIELDS = (
    "episode_id",
    "lane",
    "content_profile",
    "production_mode",
    "current_gate",
    "current_subgate",
    "last_passed_gate",
    "current_authoritative_artifact",
    "current_authoritative_sha256",
    "projection_of_ledger_event_id",
    "release_allowed",
)


def compare_and_assert(ledger_projection: dict, candidate: dict) -> None:
    """Raise StateLedgerMismatch if the candidate state disagrees with the
    ledger projection on any matched field."""
    for field_name in _MATCHED_FIELDS:
        ledger_value = ledger_projection.get(field_name)
        candidate_value = candidate.get(field_name)
        if ledger_value != candidate_value:
            raise StateLedgerMismatch(field_name, ledger_value, candidate_value)
# === END CANONICAL MODULE: state_projection.py ===

# === BEGIN CANONICAL MODULE: legacy_compat.py ===
import hashlib
import json
import re
from pathlib import Path


CANONICAL_SHORTS_HANDOFF = Path("20_script/design_handoff.json")
LEGACY_SHORTS_HANDOFFS = (
    Path("20_script/script_handoff_gate.json"),
    Path("20_script/report1_handoff.json"),
)
_SHA256_RE = re.compile(r"^[A-Fa-f0-9]{64}$")
_EVENT_ID_RE = re.compile(r"^evt-(\d{6})$")


class LegacyCompatibilityError(Exception):
    """Raised when a legacy artifact cannot be read without guessing."""


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest().upper()


def _read_json(path: Path) -> tuple[dict, str]:
    try:
        raw = path.read_bytes()
        value = json.loads(raw.decode("utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise LegacyCompatibilityError(
            f"LEGACY_ARTIFACT_UNREADABLE path={path}"
        ) from exc
    if not isinstance(value, dict):
        raise LegacyCompatibilityError(
            f"LEGACY_ARTIFACT_NOT_OBJECT path={path}"
        )
    return value, _sha256_bytes(raw)


def _resolve_inside(root: Path, relative_path: str | Path) -> Path:
    root = root.resolve()
    candidate = (root / Path(relative_path)).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise LegacyCompatibilityError(
            f"LEGACY_PATH_OUTSIDE_EPISODE path={relative_path}"
        ) from exc
    return candidate


def _pointer_target(
    episode_root: Path,
    pointer: dict,
) -> tuple[dict, str, str] | None:
    if pointer.get("schema_version") != "handoff-compat-v1":
        return None
    relative = pointer.get("canonical_handoff_path")
    expected_sha = pointer.get("canonical_handoff_sha256")
    if not isinstance(relative, str) or not _SHA256_RE.fullmatch(
        str(expected_sha or "")
    ):
        raise LegacyCompatibilityError("INVALID_LEGACY_COMPAT_POINTER")
    target = _resolve_inside(episode_root, relative)
    if not target.is_file():
        raise LegacyCompatibilityError(
            f"LEGACY_COMPAT_TARGET_MISSING path={relative}"
        )
    payload, actual_sha = _read_json(target)
    if actual_sha.upper() != str(expected_sha).upper():
        raise LegacyCompatibilityError(
            "STALE_LEGACY_CANONICAL_SHA "
            f"expected={expected_sha} actual={actual_sha}"
        )
    return payload, actual_sha, Path(relative).as_posix()


def load_shorts_handoff(episode_root: str | Path) -> dict:
    """Load the authoritative Shorts handoff without rewriting the episode.

    If the V2 canonical file exists, it is selected. Any direct legacy payload
    that differs is rejected as stale evidence rather than used. Without a
    canonical file, the first readable legacy payload (or valid compatibility
    pointer target) is returned under ``contract_mode=LEGACY_COMPAT``.
    """
    root = Path(episode_root)
    canonical_path = _resolve_inside(root, CANONICAL_SHORTS_HANDOFF)
    legacy_found: list[tuple[Path, dict, str]] = []
    for relative in LEGACY_SHORTS_HANDOFFS:
        path = _resolve_inside(root, relative)
        if path.is_file():
            payload, sha = _read_json(path)
            legacy_found.append((relative, payload, sha))

    if canonical_path.is_file():
        canonical, canonical_sha = _read_json(canonical_path)
        rejected = []
        for relative, payload, payload_sha in legacy_found:
            if payload.get("schema_version") == "handoff-compat-v1":
                agrees = (
                    payload.get("canonical_handoff_path")
                    == CANONICAL_SHORTS_HANDOFF.as_posix()
                    and str(payload.get("canonical_handoff_sha256", "")).upper()
                    == canonical_sha
                )
            else:
                agrees = payload == canonical
            if not agrees:
                rejected.append(
                    {
                        "path": relative.as_posix(),
                        "sha256": payload_sha,
                        "reason": "STALE_LEGACY_PAYLOAD",
                    }
                )
        return {
            "contract_mode": "V2_CANONICAL",
            "source_path": CANONICAL_SHORTS_HANDOFF.as_posix(),
            "source_sha256": canonical_sha,
            "payload": canonical,
            "rejected_legacy": rejected,
        }

    if not legacy_found:
        raise LegacyCompatibilityError("SHORTS_HANDOFF_NOT_FOUND")

    relative, legacy, legacy_sha = legacy_found[0]
    pointer = _pointer_target(root, legacy)
    if pointer is not None:
        payload, source_sha, source_path = pointer
    else:
        payload, source_sha, source_path = (
            legacy,
            legacy_sha,
            relative.as_posix(),
        )
    return {
        "contract_mode": "LEGACY_COMPAT",
        "source_path": source_path,
        "source_sha256": source_sha,
        "payload": payload,
        "rejected_legacy": [],
    }


def load_legacy_politics_episode(
    episode_root: str | Path,
    artifact_paths: list[str],
) -> dict:
    """Read requested legacy politics artifacts byte-for-byte, without writes."""
    root = Path(episode_root)
    artifacts = []
    for relative in artifact_paths:
        path = _resolve_inside(root, relative)
        if not path.is_file():
            raise LegacyCompatibilityError(
                f"LEGACY_POLITICS_ARTIFACT_MISSING path={relative}"
            )
        raw = path.read_bytes()
        artifacts.append(
            {
                "path": Path(relative).as_posix(),
                "sha256": _sha256_bytes(raw),
                "bytes": raw,
            }
        )
    return {
        "contract_mode": "LEGACY_COMPAT",
        "artifacts": artifacts,
    }


def append_rewind_event(
    ledger_store,
    *,
    timestamp: str,
    episode_id: str,
    lane: str,
    rewind_to_gate: str,
    reason: str,
    affected_sha256: list[str],
) -> dict:
    """Append the required LOCK_INVALIDATED evidence for one rewind."""
    if not reason.strip():
        raise LegacyCompatibilityError("REWIND_REASON_REQUIRED")
    normalized_shas = [str(value).upper() for value in affected_sha256]
    if not normalized_shas or any(
        not _SHA256_RE.fullmatch(value) for value in normalized_shas
    ):
        raise LegacyCompatibilityError("REWIND_AFFECTED_SHA256_REQUIRED")
    previous = ledger_store.latest_event_id()
    match = _EVENT_ID_RE.fullmatch(str(previous or ""))
    if match is None:
        raise LegacyCompatibilityError("REWIND_REQUIRES_EXISTING_LEDGER")
    event = {
        "event_id": f"evt-{int(match.group(1)) + 1:06d}",
        "timestamp": timestamp,
        "episode_id": episode_id,
        "lane": lane,
        "gate": rewind_to_gate,
        "event_type": "LOCK_INVALIDATED",
        "actor": "CODEX",
        "previous_event_id": previous,
        "reason": reason,
        "affected_sha256": normalized_shas,
    }
    return ledger_store.append(event)


def plan_structural_contamination_rebuild(
    *,
    structural_contamination: bool,
    target_build_path: str,
    pinned_root_path: str,
) -> dict:
    """Return a safe deterministic plan; callers own actual filesystem work."""
    if not structural_contamination:
        return {
            "status": "NO_REBUILD_REQUIRED",
            "discard_target": None,
            "rebuild_from": None,
            "partial_patch_allowed": False,
        }
    target = Path(target_build_path)
    pinned = Path(pinned_root_path)
    if target == pinned:
        raise LegacyCompatibilityError("TARGET_BUILD_MUST_NOT_BE_PINNED_ROOT")
    return {
        "status": "CLEAN_REBUILD_REQUIRED",
        "discard_target": target.as_posix(),
        "rebuild_from": pinned.as_posix(),
        "partial_patch_allowed": False,
    }
# === END CANONICAL MODULE: legacy_compat.py ===

# === BEGIN CANONICAL MODULE: gate_validation.py ===
GATE_RESULT_SCHEMA_VERSION = "gate-result-v1"

ALLOWED_AUTO_ADVANCE_CLASSES = {
    "NONE",
    "DETERMINISTIC_ONLY",
    "LLM_CALL_FORBIDDEN",
    "PAID_ACTION_FORBIDDEN",
    "UPLOAD_FORBIDDEN",
}

# Any class value outside the allowed set is treated as a forbidden attempt
# to authorize automatic LLM / paid / upload work.
FORBIDDEN_AUTO_ADVANCE_CLASSES = {
    "LLM_CALL_ALLOWED",
    "PAID_ACTION_ALLOWED",
    "UPLOAD_ALLOWED",
}


class ForbiddenAdvanceClass(Exception):
    """Raised when a validator result asks the runner to perform automatic
    LLM / paid / upload work — which the validator is never allowed to do."""

    def __init__(self, auto_advance_class: str):
        super().__init__(
            f"FORBIDDEN_ADVANCE_CLASS auto_advance_class={auto_advance_class}"
        )
        self.auto_advance_class = auto_advance_class


class PassWithErrorsForbidden(Exception):
    """Raised when a caller asks validate_gate to emit PASS while the errors
    list is non-empty. PASS is the deterministic validator's positive verdict
    and must never coexist with recorded errors."""

    def __init__(self):
        super().__init__(
            "PASS_WITH_ERRORS_FORBIDDEN: status=PASS requires empty errors"
        )


def validate_gate(
    *,
    lane: str,
    gate: str,
    subgate: str | None,
    validated_inputs: list[dict],
    evidence: list[dict],
    errors: list[dict],
    warnings: list[dict],
    next_action: str,
    auto_advance_allowed: bool,
    auto_advance_class: str,
    status: str | None = None,
    reason_code: str | None = None,
) -> dict:
    """Construct a gate_result document.

    The validator itself never executes any next action; the runner does.
    The runner must reject any result whose auto_advance_class requests
    automatic LLM, paid, or upload work.

    Authority rule: if `errors` is non-empty the status can never be PASS.
    An explicit status=PASS with non-empty errors raises
    PassWithErrorsForbidden. When status is None, it is derived as FAIL
    when errors exist and PASS otherwise.
    """
    if auto_advance_class in FORBIDDEN_AUTO_ADVANCE_CLASSES:
        raise ForbiddenAdvanceClass(auto_advance_class)
    if auto_advance_class not in ALLOWED_AUTO_ADVANCE_CLASSES:
        raise ForbiddenAdvanceClass(auto_advance_class)

    has_errors = bool(errors)
    if status == "PASS" and has_errors:
        raise PassWithErrorsForbidden()

    derived_status = status
    if derived_status is None:
        derived_status = "FAIL" if has_errors else "PASS"

    result = {
        "schema_version": GATE_RESULT_SCHEMA_VERSION,
        "status": derived_status,
        "reason_code": reason_code,
        "lane": lane,
        "gate": gate,
        "subgate": subgate,
        "validated_inputs": list(validated_inputs),
        "evidence": list(evidence),
        "errors": list(errors),
        "warnings": list(warnings),
        "next_action": next_action,
        "auto_advance_allowed": bool(auto_advance_allowed),
        "auto_advance_class": auto_advance_class,
    }
    return result
# === END CANONICAL MODULE: gate_validation.py ===

# === BEGIN CANONICAL MODULE: cost_guard.py ===
from dataclasses import dataclass


class CostOverrun(Exception):
    """Raised when a paid action would exceed the configured budget."""

    def __init__(self, kind: str, requested, limit):
        super().__init__(
            f"COST_OVERRUN kind={kind} requested={requested} limit={limit}"
        )
        self.kind = kind
        self.requested = requested
        self.limit = limit


@dataclass
class CostGuard:
    episode_budget_usd: float | None
    max_model_input_tokens_per_gate: int | None
    max_model_output_tokens_per_gate: int | None
    max_paid_tts_chars: int | None
    paid_tts_authorization: dict
    spent_tts_chars: int = 0
    spent_model_input_tokens: int = 0
    spent_model_output_tokens: int = 0
    spent_usd: float = 0.0

    def can_authorize_paid_action(self) -> bool:
        """A paid action requires both a non-zero episode budget AND an
        explicit authorization scope. No budget => no paid action."""
        if self.episode_budget_usd is None or self.episode_budget_usd <= 0:
            return False
        status = self.paid_tts_authorization.get("status")
        scope = self.paid_tts_authorization.get("scope")
        if status != "AUTHORIZED_FOR_EPISODE":
            return False
        if scope in (None, "none"):
            return False
        return True

    def can_spend_tts(self, *, chars: int) -> bool:
        """Check whether a paid TTS spend of `chars` fits within both the
        authorization limit and the episode budget."""
        if chars < 0:
            return False
        if not self.can_authorize_paid_action():
            return False
        limit = self.paid_tts_authorization.get("max_chars")
        if limit is not None and self.spent_tts_chars + chars > limit:
            return False
        if (
            self.max_paid_tts_chars is not None
            and self.spent_tts_chars + chars > self.max_paid_tts_chars
        ):
            return False
        return True

    def record_tts_spend(self, *, chars: int) -> None:
        if not self.can_spend_tts(chars=chars):
            raise CostOverrun("tts_chars", chars, self.max_paid_tts_chars)
        self.spent_tts_chars += chars

    def can_spend_model_tokens(self, *, input_tokens: int, output_tokens: int) -> bool:
        if input_tokens < 0 or output_tokens < 0:
            return False
        if self.max_model_input_tokens_per_gate is not None:
            if self.spent_model_input_tokens + input_tokens > self.max_model_input_tokens_per_gate:
                return False
        if self.max_model_output_tokens_per_gate is not None:
            if self.spent_model_output_tokens + output_tokens > self.max_model_output_tokens_per_gate:
                return False
        return True

    def authorize_paid_action(
        self,
        *,
        episode_id: str,
        action_id: str,
        cost_usd: float | None,
        chars: int | None,
        ledger_events: list[dict],
    ) -> dict:
        """Return a fail-closed authorization decision without executing.

        Authorization requires all three layers:
        1. G00 episode policy authorizes the paid scope.
        2. A USER COST_AUTHORIZED event matches the exact episode/action.
        3. The requested cost and optional character count fit both the
           event limit and remaining episode limits.
        """
        if (
            cost_usd is None
            or isinstance(cost_usd, bool)
            or not isinstance(cost_usd, (int, float))
            or cost_usd < 0
        ):
            return {"status": "STOP", "reason_code": "UNKNOWN_COST"}
        if not self.can_authorize_paid_action():
            return {"status": "STOP", "reason_code": "PAID_ACTION_NOT_AUTHORIZED"}
        if chars is not None and (
            isinstance(chars, bool) or not isinstance(chars, int) or chars < 0
        ):
            return {"status": "STOP", "reason_code": "INVALID_PAID_ACTION_SIZE"}

        matches = [
            event
            for event in ledger_events
            if event.get("event_type") == "COST_AUTHORIZED"
            and event.get("actor") == "USER"
            and event.get("episode_id") == episode_id
            and event.get("action_id") == action_id
        ]
        if not matches:
            return {
                "status": "STOP",
                "reason_code": "COST_AUTHORIZED_EVENT_REQUIRED",
            }
        event = matches[-1]
        event_limit = event.get("max_cost_usd")
        if (
            isinstance(event_limit, bool)
            or not isinstance(event_limit, (int, float))
            or event_limit < cost_usd
        ):
            return {"status": "STOP", "reason_code": "ACTION_LIMIT_EXCEEDED"}
        if self.spent_usd + cost_usd > float(self.episode_budget_usd or 0):
            return {"status": "STOP", "reason_code": "BUDGET_OVERRUN"}
        if chars is not None and not self.can_spend_tts(chars=chars):
            return {"status": "STOP", "reason_code": "TTS_CHAR_LIMIT_EXCEEDED"}
        return {
            "status": "AUTHORIZED",
            "reason_code": "COST_AUTHORIZED",
            "episode_id": episode_id,
            "action_id": action_id,
            "cost_usd": float(cost_usd),
            "chars": chars,
        }

    def record_paid_action(
        self,
        *,
        episode_id: str,
        action_id: str,
        cost_usd: float | None,
        chars: int | None,
        ledger_events: list[dict],
    ) -> dict:
        decision = self.authorize_paid_action(
            episode_id=episode_id,
            action_id=action_id,
            cost_usd=cost_usd,
            chars=chars,
            ledger_events=ledger_events,
        )
        if decision["status"] != "AUTHORIZED":
            raise CostOverrun(
                decision["reason_code"],
                cost_usd,
                self.episode_budget_usd,
            )
        self.spent_usd += float(cost_usd)
        if chars is not None:
            self.spent_tts_chars += chars
        return decision
# === END CANONICAL MODULE: cost_guard.py ===

# === BEGIN CANONICAL MODULE: context_manifest.py ===
import hashlib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path


CONTEXT_MANIFEST_SCHEMA_VERSION = "context-manifest-v1"

DEFAULT_ESTIMATOR_VERSION = "chars_div_4_v1"


class ContextPolicyViolation(Exception):
    pass


@dataclass
class ContextManifest:
    lane: str
    gate: str
    subgate: str | None
    run_id: str
    loaded_files: list[dict] = field(default_factory=list)
    excluded_by_policy: list[str] = field(default_factory=list)
    provider_input_tokens: int | None = None
    estimated_input_tokens: int | None = None
    estimator_version: str = DEFAULT_ESTIMATOR_VERSION
    unrelated_lane_reads: int = 0
    legacy_reads: int = 0
    full_srt_injected: bool = False
    contract_mode: str = "V2_CANONICAL"
    status: str = "PASS"

    def add_loaded_file(self, path: str, content: bytes | str | None = None) -> None:
        entry = {"path": path}
        if content is not None:
            if isinstance(content, str):
                content = content.encode("utf-8")
            entry["sha256"] = hashlib.sha256(content).hexdigest().upper()
            entry["chars"] = len(content)
        self.loaded_files.append(entry)

    def add_excluded(self, category: str) -> None:
        if category not in self.excluded_by_policy:
            self.excluded_by_policy.append(category)

    def set_estimated_tokens_from_chars(self, total_chars: int) -> None:
        # Simple deterministic estimator; production may override.
        self.estimated_input_tokens = max(0, total_chars // 4)
        self.estimator_version = DEFAULT_ESTIMATOR_VERSION

    def to_dict(self) -> dict:
        if self.provider_input_tokens is None and self.estimated_input_tokens is None:
            raise ValueError(
                "CONTEXT_MANIFEST_MISSING_TOKENS: set provider_input_tokens "
                "or estimated_input_tokens"
            )
        return {
            "schema_version": CONTEXT_MANIFEST_SCHEMA_VERSION,
            "lane": self.lane,
            "gate": self.gate,
            "subgate": self.subgate,
            "run_id": self.run_id,
            "loaded_files": list(self.loaded_files),
            "excluded_by_policy": list(self.excluded_by_policy),
            "provider_input_tokens": self.provider_input_tokens,
            "estimated_input_tokens": self.estimated_input_tokens,
            "estimator_version": self.estimator_version
            if self.provider_input_tokens is None
            else None,
            "unrelated_lane_reads": self.unrelated_lane_reads,
            "legacy_reads": self.legacy_reads,
            "full_srt_injected": self.full_srt_injected,
            "contract_mode": self.contract_mode,
            "status": self.status,
        }


def write_model_call_context(
    *,
    episode_root: Path,
    manifest: ContextManifest,
) -> Path:
    """Write the required manifest before a model call can be attempted."""
    identifier = re.compile(r"^[A-Za-z0-9_.-]+$")
    if (
        not identifier.fullmatch(manifest.gate)
        or not identifier.fullmatch(manifest.run_id)
        or ".." in manifest.gate
        or ".." in manifest.run_id
    ):
        raise ContextPolicyViolation("UNSAFE_CONTEXT_MANIFEST_IDENTIFIER")
    if manifest.unrelated_lane_reads != 0:
        raise ContextPolicyViolation("UNRELATED_LANE_READS_MUST_BE_ZERO")
    if manifest.legacy_reads and manifest.contract_mode != "LEGACY_COMPAT":
        raise ContextPolicyViolation("LEGACY_READS_REQUIRE_LEGACY_COMPAT")
    payload = manifest.to_dict()
    payload["model_call_ready"] = True
    target_dir = (
        Path(episode_root)
        / "90_workflow"
        / "context_manifests"
    )
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / f"{manifest.gate}-{manifest.run_id}.json"
    temporary = target.with_suffix(target.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(target)
    return target
# === END CANONICAL MODULE: context_manifest.py ===

# === BEGIN CANONICAL MODULE: runner_policy.py ===
FORBIDDEN_ADVANCE_CLASSES = {
    "LLM_CALL_ALLOWED",
    "PAID_ACTION_ALLOWED",
    "UPLOAD_ALLOWED",
}
FORBIDDEN_ACTION_MARKERS = (
    "LLM",
    "MODEL",
    "CAPCUT",
    "GUI",
    "UPLOAD",
    "RELEASE",
    "RETRY",
    "TRANSPORT",
)


def _stop(reason_code: str, detail: str | None = None) -> dict:
    result = {
        "status": "STOP",
        "reason_code": reason_code,
        "next_action": "NONE",
        "max_auto_retries": 0,
    }
    if detail is not None:
        result["detail"] = detail
    return result


def decide_runner_action(
    *,
    validator_result: dict,
    allowed_deterministic_actions: set[str],
    wait_actions: set[str],
    episode_id: str | None = None,
    paid_action: dict | None = None,
    cost_guard=None,
    ledger_events: list[dict] | None = None,
) -> dict:
    """Evaluate a validator result; never execute its next action."""
    if validator_result.get("schema_version") != "gate-result-v1":
        return _stop("INVALID_VALIDATOR_RESULT")
    advance_class = validator_result.get("auto_advance_class")
    if advance_class in FORBIDDEN_ADVANCE_CLASSES or advance_class not in {
        "NONE",
        "DETERMINISTIC_ONLY",
    }:
        return _stop("FORBIDDEN_ADVANCE_CLASS", str(advance_class))

    action = str(validator_result.get("next_action", "NONE"))
    status = validator_result.get("status")
    if action in wait_actions and status != "FAIL":
        return {
            "status": "WAIT",
            "reason_code": action,
            "next_action": action,
            "max_auto_retries": 0,
        }
    if status not in ("PASS", "NOT_REQUIRED"):
        return _stop("VALIDATOR_NOT_PASS", str(status))

    if paid_action is not None:
        if cost_guard is None or episode_id is None:
            return _stop("PAID_ACTION_POLICY_REQUIRED")
        normalized_events = getattr(ledger_events, "events", ledger_events) or []
        decision = cost_guard.authorize_paid_action(
            episode_id=episode_id,
            action_id=paid_action.get("action_id", ""),
            cost_usd=paid_action.get("cost_usd"),
            chars=paid_action.get("chars"),
            ledger_events=normalized_events,
        )
        if decision.get("status") != "AUTHORIZED":
            return _stop(decision.get("reason_code", "PAID_ACTION_REJECTED"))
        return {
            "status": "WAIT",
            "reason_code": "PAID_ACTION_AUTHORIZED_MANUAL_EXECUTION_ONLY",
            "next_action": "WAIT_PAID_ACTION_EXECUTION",
            "max_auto_retries": 0,
            "authorization": decision,
        }

    if any(marker in action.upper() for marker in FORBIDDEN_ACTION_MARKERS) or action.startswith(
        ("PAID_", "COST_")
    ):
        return _stop("FORBIDDEN_AUTO_ACTION", action)
    if action == "NONE":
        return _stop("NO_NEXT_ACTION")
    if action not in allowed_deterministic_actions:
        return _stop("ACTION_NOT_ALLOWLISTED", action)
    if validator_result.get("auto_advance_allowed") is not True:
        return _stop("AUTO_ADVANCE_NOT_ALLOWED")
    return {
        "status": "EXECUTE_DETERMINISTIC",
        "reason_code": "DETERMINISTIC_ACTION_ALLOWED",
        "next_action": action,
        "auto_advance_class": "DETERMINISTIC_ONLY",
        "max_auto_retries": 0,
    }
# === END CANONICAL MODULE: runner_policy.py ===

# === BEGIN CANONICAL MODULE: effect_policy.py ===
import hashlib


class EffectPolicyError(Exception):
    pass


def _approved_presets(pool: dict) -> list[dict]:
    presets = pool.get("presets")
    if not isinstance(presets, list):
        raise EffectPolicyError("EFFECT_POOL_PRESETS_REQUIRED")
    approved = [
        preset
        for preset in presets
        if isinstance(preset, dict)
        and preset.get("approved") is True
        and isinstance(preset.get("preset_id"), str)
        and preset["preset_id"]
    ]
    if len({preset["preset_id"] for preset in approved}) != len(approved):
        raise EffectPolicyError("DUPLICATE_EFFECT_PRESET_ID")
    return approved


def select_effect(*, pool: dict, episode_id: str, segment_id: str) -> dict:
    if pool.get("schema_version") != "effect-pool-v1":
        raise EffectPolicyError("EFFECT_POOL_SCHEMA")
    version = pool.get("preset_pool_version")
    lane = pool.get("lane")
    policy = pool.get("policy")
    if not all(isinstance(value, str) and value for value in (version, lane, policy)):
        raise EffectPolicyError("EFFECT_POOL_IDENTITY_REQUIRED")
    if policy == "NONE":
        return {
            "status": "NONE",
            "preset_id": None,
            "preset_pool_version": version,
        }
    if policy == "EXPLICIT_ONLY":
        return {
            "status": "WAIT_EXPLICIT_EFFECT_SELECTION",
            "preset_id": None,
            "preset_pool_version": version,
        }
    if (
        lane == "politics_longform"
        and policy == "SELECT_FROM_POOL"
        and pool.get("conservative") is not True
    ):
        raise EffectPolicyError("POLITICS_EFFECT_POOL_MUST_BE_CONSERVATIVE")
    approved = _approved_presets(pool)
    if policy == "LOCKED":
        locked_id = pool.get("locked_preset_id")
        if locked_id not in {preset["preset_id"] for preset in approved}:
            raise EffectPolicyError("LOCKED_EFFECT_NOT_APPROVED")
        selected = next(preset for preset in approved if preset["preset_id"] == locked_id)
    elif policy == "SELECT_FROM_POOL":
        if not approved:
            raise EffectPolicyError("NO_APPROVED_EFFECT_PRESETS")
        seed_material = f"{episode_id}{segment_id}{version}"
        digest = hashlib.sha256(seed_material.encode("utf-8")).hexdigest()
        selected = approved[int(digest, 16) % len(approved)]
    else:
        raise EffectPolicyError("UNKNOWN_EFFECT_POLICY")
    seed_material = f"{episode_id}{segment_id}{version}"
    return {
        "status": "SELECTED",
        "preset_id": selected["preset_id"],
        "preset_pool_version": version,
        "lane": lane,
        "seed_material": seed_material,
        "seed_sha256": hashlib.sha256(seed_material.encode("utf-8")).hexdigest().upper(),
    }
# === END CANONICAL MODULE: effect_policy.py ===

# === BEGIN CANONICAL MODULE: canonical_render.py ===
import hashlib
import json
import math
from typing import Any


class HumanMdCanonicalJsonMismatch(Exception):
    def __init__(self, kind: str, detail: str):
        super().__init__(f"HUMAN_MD_CANONICAL_JSON_MISMATCH kind={kind} {detail}")
        self.kind = kind
        self.detail = detail


RECORD_PREFIX = "R "


def _hash_canonical(canonical: Any) -> str:
    return hashlib.sha256(
        json.dumps(
            canonical,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
        ).encode("utf-8")
    ).hexdigest().upper()


def _collect_records(
    value: Any,
    segments: list[list[str]] | None = None,
) -> list[tuple[list[list[str]], Any]]:
    """Walk canonical recursively and return [(segments, value)] for every
    scalar leaf plus explicit markers for empty containers.

    Each segment is a ``[kind, name]`` pair where ``kind`` is ``"key"``
    (object property) or ``"idx"`` (array index, name is ``"[i]"``). This
    disambiguates ``foo[0].bar`` (idx "[0]") from an object property
    literally named ``"[0]"`` (key "[0]") — the two never collide because
    the kind tag differs (RW-P04-03 round 6).

    Containers (dict / non-empty list) produce no record of their own but
    their children carry the parent segments. Empty containers emit a
    synthetic record so adding/removing them is detectable.
    """
    if segments is None:
        segments = []
    out: list[tuple[list[list[str]], Any]] = []
    if isinstance(value, dict):
        if not value:
            out.append((list(segments), {"__empty__": "object"}))
            return out
        for k in sorted(value.keys()):
            child = [list(s) for s in segments]
            child.append(["key", str(k)])
            out.extend(_collect_records(value[k], child))
        return out
    if isinstance(value, list):
        if not value:
            out.append((list(segments), {"__empty__": "list"}))
            return out
        for i, item in enumerate(value):
            child = [list(s) for s in segments]
            child.append(["idx", f"[{i}]"])
            out.extend(_collect_records(item, child))
        return out
    # Scalar leaf — keep the original Python value so json.dumps preserves
    # the JSON type exactly (bool vs number vs string).
    out.append((list(segments), value))
    return out


def _serialize_record(segments: list[str], value: Any) -> str:
    """Encode one record as a single JSON array line."""
    return RECORD_PREFIX + json.dumps(
        [segments, value],
        ensure_ascii=False,
        allow_nan=False,
    )


def _reject_nonfinite_json_constant(constant: str) -> None:
    raise ValueError(f"non-standard JSON constant: {constant}")


def _parse_record_line(line: str) -> tuple[list[list[str]], Any] | None:
    """Parse a single record line. Returns (segments, value) or None if
    the line is not a record line.

    Each segment must be a ``[kind, name]`` pair where ``kind`` is
    ``"key"`` or ``"idx"``. Round-6 requirement: kind tag is mandatory so
    an array index never collides with an object key of the same text.
    """
    s = line.strip()
    if not s.startswith(RECORD_PREFIX):
        return None
    payload = s[len(RECORD_PREFIX):]
    try:
        rec = json.loads(
            payload,
            parse_constant=_reject_nonfinite_json_constant,
        )
    except (json.JSONDecodeError, ValueError):
        return None
    if not isinstance(rec, list) or len(rec) != 2:
        return None
    segments, value = rec
    if not isinstance(segments, list):
        return None
    for seg in segments:
        if (
            not isinstance(seg, list)
            or len(seg) != 2
            or seg[0] not in ("key", "idx")
            or not isinstance(seg[1], str)
        ):
            return None
    return segments, value


def _parse_records_from_md(md: str) -> list[tuple[list[list[str]], Any]]:
    """Parse every record line in the MD, preserving multiplicity and order."""
    out: list[tuple[list[list[str]], Any]] = []
    for raw in md.splitlines():
        rec = _parse_record_line(raw)
        if rec is not None:
            out.append(rec)
    return out


def _assert_json_compatible(value: Any, path: str = "<root>") -> None:
    """Reject values that Python can serialize to JSON but that are NOT
    themselves JSON-native. This catches:

    - tuples (Python tuple serializes to JSON array; if the caller passed
      a tuple they meant something JSON cannot represent faithfully)
    - non-string dict keys (JSON keys MUST be strings; an int/bool/None
      key would silently coerce to a string key on json.dumps and could
      collide with a real string key)

    Anything that json.dumps cannot serialize is already rejected by the
    subsequent json.dumps call (set, object, cyclic refs, etc.).
    """
    if isinstance(value, tuple):
        raise TypeError(
            f"CANONICAL_NOT_JSON_NATIVE: tuple at {path} — JSON has no tuple type"
        )
    if isinstance(value, float) and not math.isfinite(value):
        raise TypeError(
            f"CANONICAL_NOT_JSON_NATIVE: non-finite float {value!r} at {path} — "
            "JSON numbers must be finite"
        )
    if isinstance(value, dict):
        for k in value.keys():
            if not isinstance(k, str):
                raise TypeError(
                    f"CANONICAL_NOT_JSON_NATIVE: non-string dict key {k!r} at {path} — "
                    "JSON keys must be strings"
                )
        for k, v in value.items():
            _assert_json_compatible(v, f"{path}.{k}")
    elif isinstance(value, list):
        for i, item in enumerate(value):
            _assert_json_compatible(item, f"{path}[{i}]")


def render_markdown(canonical: Any) -> str:
    """Render canonical JSON to deterministic markdown with lossless record
    encoding."""
    # Round 8: reject Python-native-but-not-JSON-native inputs (tuples,
    # non-string dict keys) BEFORE they silently coerce through json.dumps.
    _assert_json_compatible(canonical)
    # Round-trip through json for deterministic key ordering and to reject
    # non-JSON-serializable input early.
    serialized = json.dumps(
        canonical,
        sort_keys=True,
        ensure_ascii=False,
        allow_nan=False,
    )
    canonical_norm = json.loads(serialized)
    sha = _hash_canonical(canonical_norm)

    records = _collect_records(canonical_norm)
    # Sort records by (segments, json(value)) for deterministic output that
    # is independent of insertion order.
    records.sort(
        key=lambda r: (
            r[0],
            json.dumps(
                r[1],
                sort_keys=True,
                ensure_ascii=False,
                allow_nan=False,
            ),
        )
    )

    title = (
        canonical_norm.get("schema_version")
        if isinstance(canonical_norm, dict)
        else None
    ) or "canonical-json"

    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("<!-- Rendered from canonical JSON. Do not edit. -->")
    lines.append("<!-- Each 'R ' line below is one JSON record [segments, value].")
    lines.append("     Reconciliation parses those records and compares them")
    lines.append("     losslessly as a sorted, multiplicity-preserving list. -->")
    lines.append("")
    lines.append("## Records")
    lines.append("")
    for segments, value in records:
        lines.append(_serialize_record(segments, value))
    lines.append("")
    lines.append(f"<!-- CANONICAL_SHA256: {sha} -->")
    lines.append("")
    return "\n".join(lines)


def reconcile_human_md(*, canonical: Any, human_md: str) -> dict:
    """Compare a hand-edited MD against the canonical JSON projection.

    Strategy (RW-P04-03 round 5, lossless codec):
    - Build the canonical record list (segments, value) preserving type
      and multiplicity.
    - Parse the human MD's R-lines into the same shape.
    - Sort both lists (canonical key for sorted order) and compare element
      by element. Set semantics are explicitly forbidden: duplicate lines
      and structural collisions must be caught.

    Outcomes:
    - IN_SYNC: the human MD is byte-identical to a fresh canonical render.
    - COSMETIC_DIFF_ONLY: the record lists are identical (same scalars,
      same multiplicity) but the surrounding MD text differs.
    - HumanMdCanonicalJsonMismatch: the record lists differ.
    """
    # Round 8: reject non-JSON-native canonical inputs on this path too.
    _assert_json_compatible(canonical)
    canonical_norm = json.loads(
        json.dumps(
            canonical,
            sort_keys=True,
            ensure_ascii=False,
            allow_nan=False,
        )
    )
    canonical_records = _collect_records(canonical_norm)
    human_records = _parse_records_from_md(human_md)

    # Comparison key: canonical-form JSON of (segments, value). We compare
    # the JSON-serialized form rather than the Python objects so that
    # distinct JSON values that compare equal in Python (e.g. int 1 and
    # float 1.0, or 0 and False) are correctly distinguished. The key is
    # also hashable for the multiplicity counter below.
    def _key(rec: tuple[list[list[str]], Any]) -> tuple:
        segments, value = rec
        segments_tuple = tuple(tuple(s) for s in segments)
        return (
            segments_tuple,
            json.dumps(
                value,
                sort_keys=True,
                ensure_ascii=False,
                allow_nan=False,
            ),
        )

    canonical_keys = sorted(_key(r) for r in canonical_records)
    human_keys = sorted(_key(r) for r in human_records)

    if canonical_keys == human_keys:
        # Record lists identical at the JSON-fidelity level. Now decide
        # IN_SYNC vs COSMETIC_DIFF_ONLY by comparing the surrounding MD
        # text against a fresh render.
        fresh = render_markdown(canonical)
        if human_md.strip() == fresh.strip():
            return {"status": "IN_SYNC", "action": "NONE"}
        return {"status": "COSMETIC_DIFF_ONLY", "action": "RE_RENDER_RECOMMENDED"}

    # Record lists differ. Classify the difference for the error message.
    canonical_count: dict[tuple, int] = {}
    for k in canonical_keys:
        canonical_count[k] = canonical_count.get(k, 0) + 1
    human_count: dict[tuple, int] = {}
    for k in human_keys:
        human_count[k] = human_count.get(k, 0) + 1

    missing = [
        k for k, n in canonical_count.items() if human_count.get(k, 0) < n
    ]
    extra = [
        k for k, n in human_count.items() if canonical_count.get(k, 0) < n
    ]
    # Render a short readable preview of the first few diffs.
    def _preview(key_tuple: tuple) -> str:
        segments_tuple, value_json = key_tuple
        # segments_tuple is a tuple of (kind, name) tuples.
        path = "/".join(
            f"{kind}:{name}" for kind, name in segments_tuple
        ) if segments_tuple else "<root>"
        return f"{path}={value_json}"

    detail = (
        f"missing_or_underrepresented={[ _preview(k) for k in missing[:5] ]} "
        f"extra_or_overrepresented={[ _preview(k) for k in extra[:5] ]} "
        f"(canonical_records={len(canonical_keys)} "
        f"human_records={len(human_keys)})"
    )
    raise HumanMdCanonicalJsonMismatch("STRUCTURAL_OR_VALUE_CHANGE", detail)
# === END CANONICAL MODULE: canonical_render.py ===

# === BEGIN CANONICAL MODULE: prompt_factory.py ===
import hashlib
import json
from dataclasses import dataclass, field
from typing import Any


PROMPT_MANIFEST_SCHEMA_VERSION = "prompt-packet-manifest-v1"
ANALYSIS_CACHE_SCHEMA_VERSION = "analysis-cache-manifest-v1"


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest().upper()


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest().upper()


# ---------------------------------------------------------------------------
# Prompt Factory
# ---------------------------------------------------------------------------


def _content_address_key(
    *,
    template_sha256: str,
    input_artifacts: list[dict],
    included_segment_ids: list[str],
    excluded_fields: list[str],
    language_quality_contract_sha: str,
    external_authority_contract_sha: str,
) -> str:
    """Stable content-addressed key for prompt-packet reuse."""
    payload = json.dumps(
        {
            "template_sha256": template_sha256,
            "input_artifacts": [
                {"path": a["path"], "sha256": a["sha256"]} for a in input_artifacts
            ],
            "included_segment_ids": list(included_segment_ids),
            "excluded_fields": sorted(excluded_fields),
            "language_quality_contract_sha256": language_quality_contract_sha,
            "external_authority_contract_sha256": external_authority_contract_sha,
        },
        sort_keys=True,
        ensure_ascii=False,
    )
    return _sha256_text(payload)


def build_prompt(
    *,
    template_path: str,
    template_text: str,
    inputs: list[dict],
    included_segment_ids: list[str],
    excluded_fields: list[str],
    language_quality_contract: str,
    external_authority_contract: str,
) -> dict:
    """Build an external prompt packet + manifest.

    inputs: list of {path, content} dicts. Content may be str or bytes.
    The packet body is deterministic: template, then inputs in given order,
    then the shared contracts appended.

    The manifest records the content-addressed packet SHA so callers can
    reuse the same packet when the key matches.
    """
    if not isinstance(template_text, str):
        raise TypeError("template_text must be str")
    template_sha = _sha256_text(template_text)

    input_artifacts: list[dict] = []
    input_bodies: list[str] = []
    for inp in inputs:
        path = inp["path"]
        content = inp["content"]
        if isinstance(content, str):
            content_bytes = content.encode("utf-8")
        elif isinstance(content, (bytes, bytearray)):
            content_bytes = bytes(content)
        else:
            raise TypeError(f"input content must be str or bytes: {path}")
        sha = _sha256_bytes(content_bytes)
        input_artifacts.append({"path": path, "sha256": sha})
        input_bodies.append(
            f"--- INPUT: {path} (sha256={sha}) ---\n{content_bytes.decode('utf-8', errors='replace')}"
        )

    lq_text = ""
    lq_sha = ""
    if language_quality_contract:
        try:
            from pathlib import Path

            lq_text = Path(language_quality_contract).read_text(encoding="utf-8")
            lq_sha = _sha256_text(lq_text)
        except OSError:
            lq_text = ""
            lq_sha = ""

    ea_text = ""
    ea_sha = ""
    if external_authority_contract:
        try:
            from pathlib import Path

            ea_text = Path(external_authority_contract).read_text(encoding="utf-8")
            ea_sha = _sha256_text(ea_text)
        except OSError:
            ea_text = ""
            ea_sha = ""

    # Compose the packet in a fixed order.
    parts: list[str] = []
    parts.append("# External Prompt Packet")
    parts.append("")
    parts.append(f"<!-- template_path: {template_path} -->")
    parts.append(f"<!-- template_sha256: {template_sha} -->")
    parts.append("")
    parts.append("## Template")
    parts.append("")
    parts.append(template_text.strip())
    parts.append("")
    if included_segment_ids:
        parts.append("## Included Segment IDs")
        parts.append("")
        for sid in included_segment_ids:
            parts.append(f"- {sid}")
        parts.append("")
    if excluded_fields:
        parts.append("## Excluded Fields (do not surface to external model)")
        parts.append("")
        for f in excluded_fields:
            parts.append(f"- {f}")
        parts.append("")
    parts.append("## Inputs")
    parts.append("")
    parts.extend(input_bodies)
    parts.append("")
    if lq_text:
        parts.append("## Shared Language Quality Contract")
        parts.append("")
        parts.append(lq_text.strip())
        parts.append("")
    if ea_text:
        parts.append("## Shared External Authority Contract")
        parts.append("")
        parts.append(ea_text.strip())
        parts.append("")

    packet_text = "\n".join(parts)
    packet_sha = _sha256_text(packet_text)

    content_key = _content_address_key(
        template_sha256=template_sha,
        input_artifacts=input_artifacts,
        included_segment_ids=included_segment_ids,
        excluded_fields=excluded_fields,
        language_quality_contract_sha=lq_sha,
        external_authority_contract_sha=ea_sha,
    )

    manifest = {
        "schema_version": PROMPT_MANIFEST_SCHEMA_VERSION,
        "template_path": template_path,
        "template_sha256": template_sha,
        "language_quality_contract_path": language_quality_contract or None,
        "language_quality_contract_sha256": lq_sha or None,
        "external_authority_contract_path": external_authority_contract or None,
        "external_authority_contract_sha256": ea_sha or None,
        "input_artifacts": input_artifacts,
        "included_segment_ids": list(included_segment_ids),
        "excluded_fields": list(excluded_fields),
        "content_addressed_key": content_key,
        "packet_sha256": packet_sha,
        "packet_text": packet_text,
    }
    return {"packet_text": packet_text, "manifest": manifest}


# ---------------------------------------------------------------------------
# Analysis cache
# ---------------------------------------------------------------------------


@dataclass
class _LayerInputs:
    """Which upstream inputs each cache layer depends on. Used by the
    invalidation planner to invalidate only the affected layer."""

    transcript_segments: tuple[str, ...] = ("source_sha256",)
    ocr_segments: tuple[str, ...] = ("source_sha256", "tool_versions.ocr")
    scene_segments: tuple[str, ...] = (
        "source_sha256",
        "tool_versions.scene",
        "sampling_policy.frame_sample_fps",
    )
    motion_segments: tuple[str, ...] = (
        "source_sha256",
        "tool_versions.scene",
        "sampling_policy.frame_sample_fps",
    )
    speaker_segments: tuple[str, ...] = ("source_sha256",)
    audio_event_segments: tuple[str, ...] = ("source_sha256",)


_LAYER_DEPS = _LayerInputs()


def _layer_depends_on(layer_name: str) -> tuple[str, ...]:
    return getattr(_LAYER_DEPS, layer_name, ("source_sha256",))


def _cache_key_payload(
    *,
    source_sha256: str,
    duration_us: int,
    resolution: str,
    selected_range: dict,
    profile_version: str,
    tool_versions: dict,
    sampling_policy: dict,
) -> str:
    return json.dumps(
        {
            "source_sha256": source_sha256,
            "duration_us": duration_us,
            "resolution": resolution,
            "selected_range": selected_range,
            "profile_version": profile_version,
            "tool_versions": tool_versions,
            "sampling_policy": sampling_policy,
        },
        sort_keys=True,
        ensure_ascii=False,
    )


def build_analysis_cache_manifest(
    *,
    source_sha256: str,
    duration_us: int,
    resolution: str,
    selected_range: dict,
    profile_version: str,
    tool_versions: dict,
    sampling_policy: dict,
    layers: dict,
    external_analysis: dict | None = None,
) -> dict:
    """Build an analysis-cache manifest.

    external_analysis, when provided, is treated as optional supplementary
    input. If it disagrees with local primary evidence on a tracked hash
    (e.g. transcript_sha256), the manifest records
    external_analysis_status=EXTERNAL_ANALYSIS_MISMATCH and does NOT adopt
    the external result.
    """
    if not isinstance(layers, dict) or not layers:
        raise ValueError("ANALYSIS_CACHE_EMPTY_LAYERS")
    for layer_name, layer in layers.items():
        if "sha256" not in layer:
            raise ValueError(f"ANALYSIS_CACHE_LAYER_MISSING_SHA: {layer_name}")

    key = _sha256_text(
        _cache_key_payload(
            source_sha256=source_sha256,
            duration_us=duration_us,
            resolution=resolution,
            selected_range=selected_range,
            profile_version=profile_version,
            tool_versions=tool_versions,
            sampling_policy=sampling_policy,
        )
    )

    external_status = "NOT_PROVIDED"
    if external_analysis is not None:
        # Compare any tracked hash the external result claims against the
        # local layer hash of the same name.
        external_status = "ACCEPTED_SUPPLEMENTARY"
        for ext_key, local_layer in (
            ("transcript_sha256", "transcript_segments"),
            ("ocr_sha256", "ocr_segments"),
            ("scene_sha256", "scene_segments"),
        ):
            if ext_key in external_analysis and local_layer in layers:
                if external_analysis[ext_key] != layers[local_layer]["sha256"]:
                    external_status = "EXTERNAL_ANALYSIS_MISMATCH"
                    break

    return {
        "schema_version": ANALYSIS_CACHE_SCHEMA_VERSION,
        "cache_key_sha256": key,
        "source_sha256": source_sha256,
        "duration_us": duration_us,
        "resolution": resolution,
        "selected_range": selected_range,
        "profile_version": profile_version,
        "tool_versions": dict(tool_versions),
        "sampling_policy": dict(sampling_policy),
        "layers": dict(layers),
        "external_analysis": external_analysis,
        "external_analysis_status": external_status,
    }


def plan_cache_invalidation(
    *,
    current_manifest: dict,
    new_inputs: dict,
) -> dict:
    """Decide which layers to invalidate when inputs change.

    Cache-key components (all trigger full invalidation when changed):
    - source_sha256
    - duration_us
    - resolution
    - selected_range
    - profile_version

    Per-layer inputs (trigger only dependent layers):
    - tool_versions.<x>
    - sampling_policy.<key>

    RW-P04-02: every cache-key component change must invalidate all layers,
    because the cache key itself is no longer valid.
    """
    current_source = current_manifest.get("source_sha256")
    new_source = new_inputs.get("source_sha256")
    if current_source != new_source:
        return {
            "invalidate": sorted(current_manifest.get("layers", {}).keys()),
            "reason": "SOURCE_SHA256_CHANGED",
        }

    # Any cache-key component change invalidates every layer (the cache key
    # itself changed, so no cached layer is reusable).
    cache_key_fields = ("duration_us", "resolution", "selected_range", "profile_version")
    for field in cache_key_fields:
        if current_manifest.get(field) != new_inputs.get(field):
            return {
                "invalidate": sorted(current_manifest.get("layers", {}).keys()),
                "reason": f"CACHE_KEY_FIELD_CHANGED:{field}",
            }

    invalidate: set[str] = set()
    current_tools = current_manifest.get("tool_versions", {})
    new_tools = new_inputs.get("tool_versions", {})
    current_sampling = current_manifest.get("sampling_policy", {})
    new_sampling = new_inputs.get("sampling_policy", {})

    sampling_changed = current_sampling != new_sampling

    for layer_name in current_manifest.get("layers", {}).keys():
        deps = _layer_depends_on(layer_name)
        for dep in deps:
            if dep == "source_sha256":
                continue
            if dep.startswith("tool_versions."):
                tool_key = dep.split(".", 1)[1]
                if current_tools.get(tool_key) != new_tools.get(tool_key):
                    invalidate.add(layer_name)
                    break
            elif dep.startswith("sampling_policy."):
                if sampling_changed:
                    invalidate.add(layer_name)
                    break

    return {
        "invalidate": sorted(invalidate),
        "reason": "PARTIAL_INVALIDATION",
    }
# === END CANONICAL MODULE: prompt_factory.py ===


# WORKFLOW_HARNESS_SOURCE_VERSION = 'shared-gates-separated-lanes-v2'
# WORKFLOW_HARNESS_SOURCE_SHA256 = '5787058342436A2C334E318E9F4AE7801DD34AA01075C2AFD3C68A9EAFC94DB2'
# DO NOT EDIT — regenerate via scripts/sync_shared_workflow_harness.py
